import { card, heading, money } from './checkoutHelpers'
import type { Loyalty, OrderType } from './checkoutHelpers'

export function LoyaltyBanner(p: { loyalty: Loyalty | null; orderType: OrderType }) {
  const l = p.loyalty
    if (!l || l.needed <= 0) return null

      const win = l.qualifies
        return (
            <div
                  style={{
                          ...card,
                                  background: win ? '#e8f5e9' : '#fff8e1',
                                          border: `1.5px solid ${win ? '#43a047' : '#ffca28'}`,
                                                }}
                                                    >
                                                          {win ? (
                                                                  <>
                                                                            <strong style={{ fontSize: 17 }}>🎉 Loyalty reward unlocked!</strong>
                                                                                      <div style={{ fontSize: 15, marginTop: 4 }}>
                                                                                                  {l.reward_type === 'free_delivery'
                                                                                                                ? p.orderType === 'delivery'
                                                                                                                                ? 'Your delivery is free on this order.'
                                                                                                                                                : 'Choose Delivery to get free delivery on this order.'
                                                                                                                                                              : `You get up to ${money(Number(l.reward_value))} off your food.`}
                                                                                                                                                                        </div>
                                                                                                                                                                                </>
                                                                                                                                                                                      ) : (
                                                                                                                                                                                              <>
                                                                                                                                                                                                        <strong style={{ fontSize: 16 }}>⭐ Loyalty progress</strong>
                                                                                                                                                                                                                  <div style={{ fontSize: 15, marginTop: 4 }}>
                                                                                                                                                                                                                              {l.order_count} of {l.needed} orders. Keep ordering to earn a reward!
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                            function Row(p: { name: string; value: string; color?: string }) {
                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                display: 'flex',
                                                                                                                                                                                                                                                                                        justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                fontSize: 16,
                                                                                                                                                                                                                                                                                                        padding: '4px 0',
                                                                                                                                                                                                                                                                                                                color: p.color,
                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                <span>{p.name}</span>
                                                                                                                                                                                                                                                                                                                                      <span>{p.value}</span>
                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            interface SummaryProps {
                                                                                                                                                                                                                                                                                                                                              orderType: OrderType
                                                                                                                                                                                                                                                                                                                                                subtotal: number
                                                                                                                                                                                                                                                                                                                                                  deliveryFee: number
                                                                                                                                                                                                                                                                                                                                                    takeawayFee: number
                                                                                                                                                                                                                                                                                                                                                      discount: number; serviceCharge?: number; vat?: number
                                                                                                                                                                                                                                                                                                                                                        total: number
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        export function SummaryCard(p: SummaryProps) {
                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                              <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                    <h3 style={heading}>Summary</h3>
                                                                                                                                                                                                                                                                                                                                                                          <Row name="Subtotal" value={money(p.subtotal)} />
                                                                                                                                                                                                                                                                                                                                                                                {p.orderType === 'delivery' && (
                                                                                                                                                                                                                                                                                                                                                                                        <Row name="Delivery fee" value={p.deliveryFee > 0 ? money(p.deliveryFee) : 'Free'} />
                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                    {p.orderType === 'takeaway' && p.takeawayFee > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                            <Row name="Takeaway pack" value={money(p.takeawayFee)} />
                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                  {(p.serviceCharge ?? 0) > 0 && <Row name="Service charge" value={money(p.serviceCharge ?? 0)} />}
                                                                                                                                                                                                                                                                                                                                                                                                                  {(p.vat ?? 0) > 0 && <Row name="VAT" value={money(p.vat ?? 0)} />}
                                                                                                                                                                                                                                                                                                                                                                                                                        {p.discount > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                <Row name="Loyalty reward" value={`− ${money(p.discount)}`} color="#2e7d32" />
                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      paddingTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginTop: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderTop: '1px solid #eee',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>Total</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{money(p.total)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export function PayBar(p: { canPay: boolean; total: number; accent: string; onPay: () => void }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        position: 'fixed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                left: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        right: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bottom: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderTop: '1px solid #e8e2dc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: '12px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paddingBottom: 'calc(12px + env(safe-area-inset-bottom, 0px))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ maxWidth: 520, margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={p.onPay}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!p.canPay}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '15px 20px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: p.canPay ? p.accent : '#c9c3bd',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cursor: p.canPay ? 'pointer' : 'not-allowed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Proceed to Payment · {money(p.total)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  