import { COUNTRIES, card, heading, label, input, errorText, money } from './checkoutHelpers'
import type { OrderType, RestaurantInfo } from './checkoutHelpers'

interface OrderTypeProps {
  orderType: OrderType
    setOrderType: (t: OrderType) => void
      table: string | null
        restaurant: RestaurantInfo | null
          accent: string
          }

          export function OrderTypeCard(p: OrderTypeProps) {
            const takeaway = Number(p.restaurant?.takeaway_fee ?? 0)
              const delivery = Number(p.restaurant?.delivery_fee ?? 0)
                const types: { key: OrderType; icon: string; title: string; note: string }[] = [
                    { key: 'dine_in', icon: '🍽️', title: 'Dine-in', note: 'No extra fee' },
                        {
                              key: 'takeaway',
                                    icon: '🥡',
                                          title: 'Takeaway',
                                                note: takeaway > 0 ? `Pack ${money(takeaway)}` : 'No pack fee',
                                                    },
                                                        {
                                                              key: 'delivery',
                                                                    icon: '🛵',
                                                                          title: 'Delivery',
                                                                                note: delivery > 0 ? `Fee ${money(delivery)}` : 'Free',
                                                                                    },
                                                                                      ]

                                                                                        return (
                                                                                            <div style={card}>
                                                                                                  <h3 style={heading}>Order Type</h3>
                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
                                                                                                                {types.map((t) => {
                                                                                                                          const active = p.orderType === t.key
                                                                                                                                    return (
                                                                                                                                                <button
                                                                                                                                                              key={t.key}
                                                                                                                                                                            onClick={() => p.setOrderType(t.key)}
                                                                                                                                                                                          style={{
                                                                                                                                                                                                          padding: '12px 4px',
                                                                                                                                                                                                                          borderRadius: 12,
                                                                                                                                                                                                                                          border: `2px solid ${active ? p.accent : '#e2ddd8'}`,
                                                                                                                                                                                                                                                          background: active ? p.accent : '#fff',
                                                                                                                                                                                                                                                                          color: active ? '#fff' : '#2b1b12',
                                                                                                                                                                                                                                                                                          cursor: 'pointer',
                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: 22 }}>{t.icon}</div>
                                                                                                                                                                                                                                                                                                                                                <div style={{ fontSize: 15, fontWeight: 700 }}>{t.title}</div>
                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 13, opacity: 0.85 }}>{t.note}</div>
                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                        {p.orderType === 'dine_in' && (
                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ margin: '12px 0 0', fontSize: 15, color: '#4a4a4a' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                          {p.table
                                                                                                                                                                                                                                                                                                                                                                                                                                      ? `📍 Table ${p.table}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                  : 'Table not detected. Please tell staff your table number.'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      interface DetailsProps {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        orderType: OrderType
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setName: (v: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              countryCode: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setCountryCode: (v: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  phone: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setPhone: (v: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      phoneOk: boolean
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        address: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setAddress: (v: string) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export function DetailsCard(p: DetailsProps) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const ng = p.countryCode === '+234'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={card}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 style={heading}>Your Details</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label style={{ ...label, marginTop: 0 }}>Full name</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="e.g. Ade Ojo"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={p.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => p.setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    autoComplete="name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label style={label}>Phone number</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', gap: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={p.countryCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => p.setCountryCode(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ ...input, width: 118, padding: '12px 6px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {COUNTRIES.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option key={c.code} value={c.code}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {c.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder={ng ? '803 123 4567' : 'Phone number'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={p.phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => p.setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              inputMode="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        autoComplete="tel-national"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {p.phone.length > 0 && !p.phoneOk && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={errorText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {ng
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ? 'Enter a valid Nigerian mobile number, e.g. 0803 123 4567.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : 'Enter a valid phone number.'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {p.orderType === 'delivery' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label style={label}>Delivery address</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="House number, street, area"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={p.address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => p.setAddress(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rows={2}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ ...input, resize: 'none' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          