import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import type { CartItem } from '../../hooks/useCart'

export default function Checkout() {
  const { restaurantSlug } = useParams()
    const navigate = useNavigate()

      const [items, setItems] = useState<CartItem[]>([])
        const [orderType, setOrderType] = useState<'dine_in' | 'takeaway' | 'delivery'>('dine_in')
          const [table, setTable] = useState<string | null>(null)
            const [name, setName] = useState('')
              const [phone, setPhone] = useState('')
                const [address, setAddress] = useState('')

                  useEffect(() => {
                      const stored = sessionStorage.getItem('cart')
                          if (stored) setItems(JSON.parse(stored))
                              const storedTable = sessionStorage.getItem('table')
                                  if (storedTable) {
                                        setTable(storedTable)
                                              setOrderType('dine_in')
                                                  }
                                                    }, [])

                                                      const subtotal = items.reduce((sum, i) => sum + i.price * i.quantity, 0)
                                                        const deliveryFee = orderType === 'delivery' ? 500 : 0
                                                          const total = subtotal + deliveryFee

                                                            function proceedToPayment() {
                                                                sessionStorage.setItem(
                                                                      'checkoutDetails',
                                                                            JSON.stringify({ orderType, table, name, phone, address, subtotal, deliveryFee, total })
                                                                                )
                                                                                    navigate(`/r/${restaurantSlug}/pay`)
                                                                                      }

                                                                                        if (items.length === 0) {
                                                                                            return (
                                                                                                  <div style={{ padding: 24 }}>
                                                                                                          <p>Your cart is empty.</p>
                                                                                                                  <button onClick={() => navigate(`/r/${restaurantSlug}`)}>Back to Menu</button>
                                                                                                                        </div>
                                                                                                                            )
                                                                                                                              }

                                                                                                                                return (
                                                                                                                                    <div style={{ maxWidth: 480, margin: '0 auto', padding: 16, paddingBottom: 100 }}>
                                                                                                                                          <h1>Checkout</h1>

                                                                                                                                                <h3>Your Order</h3>
                                                                                                                                                      {items.map((item) => (
                                                                                                                                                              <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0' }}>
                                                                                                                                                                        <span>{item.name} × {item.quantity}</span>
                                                                                                                                                                                  <span>₦{item.price * item.quantity}</span>
                                                                                                                                                                                          </div>
                                                                                                                                                                                                ))}

                                                                                                                                                                                                      <h3>Order Type</h3>
                                                                                                                                                                                                            <div style={{ marginBottom: 12 }}>
                                                                                                                                                                                                                    <label style={{ marginRight: 12 }}>
                                                                                                                                                                                                                              <input type="radio" checked={orderType === 'dine_in'} onChange={() => setOrderType('dine_in')} /> Dine-in
                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                              <label style={{ marginRight: 12 }}>
                                                                                                                                                                                                                                                        <input type="radio" checked={orderType === 'takeaway'} onChange={() => setOrderType('takeaway')} /> Takeaway
                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                        <label>
                                                                                                                                                                                                                                                                                  <input type="radio" checked={orderType === 'delivery'} onChange={() => setOrderType('delivery')} /> Delivery
                                                                                                                                                                                                                                                                                          </label>
                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                      {orderType === 'dine_in' && (
                                                                                                                                                                                                                                                                                                              <p>Table: {table || 'Not specified — please tell staff your table number'}</p>
                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                          <h3>Your Details</h3>
                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                        placeholder="Full name"
                                                                                                                                                                                                                                                                                                                                                value={name}
                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                style={{ display: 'block', width: '100%', padding: 8, marginBottom: 8 }}
                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Phone number"
                                                                                                                                                                                                                                                                                                                                                                                            value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                            style={{ display: 'block', width: '100%', padding: 8, marginBottom: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                        {orderType === 'delivery' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Delivery address"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setAddress(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{ display: 'block', width: '100%', padding: 8, marginBottom: 8 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: 16, borderTop: '1px solid #ddd', paddingTop: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>Subtotal</span><span>₦{subtotal}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {deliveryFee > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>Delivery fee</span><span>₦{deliveryFee}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Total</span><span>₦{total}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={proceedToPayment}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!name.trim() || !phone.trim()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ marginTop: 16, padding: '12px 24px', width: '100%' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Proceed to Payment
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              