import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import type { CartItem } from '../../hooks/useCart'

type CheckoutDetails = {
  orderType: 'dine_in' | 'takeaway' | 'delivery'
    table: string | null
      name: string
        phone: string
          address?: string
          }

          export default function Pay() {
            const { restaurantSlug } = useParams()
              const navigate = useNavigate()

                const [items, setItems] = useState<CartItem[]>([])
                  const [details, setDetails] = useState<CheckoutDetails | null>(null)
                    const [email, setEmail] = useState('')
                      const [loading, setLoading] = useState(false)
                        const [error, setError] = useState('')

                          useEffect(() => {
                              const storedCart = sessionStorage.getItem('cart')
                                  const storedDetails = sessionStorage.getItem('checkoutDetails')
                                      if (storedCart) setItems(JSON.parse(storedCart))
                                          if (storedDetails) setDetails(JSON.parse(storedDetails))
                                            }, [])

                                              const subtotal = items.reduce((sum, i) => sum + i.price * i.quantity, 0)
                                                const deliveryFee = details?.orderType === 'delivery' ? 500 : 0
                                                  const total = subtotal + deliveryFee

                                                    async function handlePayNow() {
                                                        setError('')

                                                            if (!email.trim()) {
                                                                  setError('Please enter your email address')
                                                                        return
                                                                            }
                                                                                if (!details || items.length === 0) {
                                                                                      setError('Missing order details. Please go back to checkout.')
                                                                                            return
                                                                                                }

                                                                                                    setLoading(true)

                                                                                                        try {
                                                                                                              const { data: restaurant, error: restaurantErr } = await supabase
                                                                                                                      .from('restaurants')
                                                                                                                              .select('id')
                                                                                                                                      .eq('slug', restaurantSlug)
                                                                                                                                              .single()

                                                                                                                                                    if (restaurantErr || !restaurant) {
                                                                                                                                                            throw new Error('Restaurant not found')
                                                                                                                                                                  }

                                                                                                                                                                        // Resolve table_id for dine-in orders
                                                                                                                                                                              let tableId: string | null = null
                                                                                                                                                                                    if (details.orderType === 'dine_in' && details.table) {
                                                                                                                                                                                            const { data: table } = await supabase
                                                                                                                                                                                                      .from('tables')
                                                                                                                                                                                                                .select('id')
                                                                                                                                                                                                                          .eq('restaurant_id', restaurant.id)
                                                                                                                                                                                                                                    .eq('table_number', details.table)
                                                                                                                                                                                                                                              .single()

                                                                                                                                                                                                                                                      tableId = table?.id ?? null
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                  const orderNumber = `ORD-${Date.now()}`

                                                                                                                                                                                                                                                                        const { data: order, error: orderErr } = await supabase
                                                                                                                                                                                                                                                                                .from('orders')
                                                                                                                                                                                                                                                                                        .insert({
                                                                                                                                                                                                                                                                                                  restaurant_id: restaurant.id,
                                                                                                                                                                                                                                                                                                            table_id: tableId,
                                                                                                                                                                                                                                                                                                                      order_number: orderNumber,
                                                                                                                                                                                                                                                                                                                                order_type: details.orderType,
                                                                                                                                                                                                                                                                                                                                          status: 'pending',
                                                                                                                                                                                                                                                                                                                                                    payment_status: 'pending',
                                                                                                                                                                                                                                                                                                                                                              subtotal,
                                                                                                                                                                                                                                                                                                                                                                        delivery_fee: deliveryFee,
                                                                                                                                                                                                                                                                                                                                                                                  discount: 0,
                                                                                                                                                                                                                                                                                                                                                                                            total,
                                                                                                                                                                                                                                                                                                                                                                                                      delivery_name: details.name,
                                                                                                                                                                                                                                                                                                                                                                                                                delivery_phone: details.phone,
                                                                                                                                                                                                                                                                                                                                                                                                                          delivery_address: details.address ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                          .select('id')
                                                                                                                                                                                                                                                                                                                                                                                                                                                  .single()

                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (orderErr || !order) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                throw new Error(orderErr?.message || 'Could not create order')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const orderItemsPayload = items.map((item) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    restaurant_id: restaurant.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            order_id: order.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    menu_item_id: item.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item_name: item.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    item_price: item.price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quantity: item.quantity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { error: itemsErr } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .from('order_items')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .insert(orderItemsPayload)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (itemsErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      throw new Error(itemsErr.message)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const callbackUrl = `${window.location.origin}/r/${restaurantSlug}/order-confirmation`

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const res = await fetch(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'https://dpfgurqoogjintzqqzcx.supabase.co/functions/v1/initialize-payment',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ order_id: order.id, email, callback_url: callbackUrl }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = await res.json()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!res.ok || !data.authorization_url) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  throw new Error(data.error || 'Could not start payment')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.location.href = data.authorization_url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setError(err instanceof Error ? err.message : 'Something went wrong')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setLoading(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (items.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ padding: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Your cart is empty.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => navigate(`/r/${restaurantSlug}`)}>Back to menu</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>Payment</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {items.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{item.name} × {item.quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>₦{item.price * item.quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700, marginTop: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>Total</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>₦{total}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Email address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ display: 'block', width: '100%', padding: 8, marginTop: 4, marginBottom: 16 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {error && <p style={{ color: 'red' }}>{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={handlePayNow} disabled={loading} style={{ padding: '12px 24px', width: '100%' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? 'Processing...' : 'Pay Now'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          