import { useEffect, useMemo, useState } from 'react'
import { useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'
import { useCart } from '../../hooks/useCart'
import type { Category, MenuItem, Restaurant } from './menuHelpers'
import { MenuItemCard } from './MenuItemCard'
import { Hero, SearchAndTabs, CartBar } from './MenuChrome'

type Section = { id: string; name: string; items: MenuItem[] }

export default function RestaurantMenu() {
  const { restaurantSlug } = useParams()
    const [searchParams] = useSearchParams()
      const tableParam = searchParams.get('table')
        const navigate = useNavigate()

          const [restaurant, setRestaurant] = useState<Restaurant | null>(null)
            const [categories, setCategories] = useState<Category[]>([])
              const [items, setItems] = useState<MenuItem[]>([])
                const [loading, setLoading] = useState(true)
                  const [notFound, setNotFound] = useState(false)
                    const [search, setSearch] = useState('')
                      const [activeCat, setActiveCat] = useState('all')

                        const cart = useCart()

                          useEffect(() => {
                              async function load() {
                                    const { data: rest } = await supabase
                                            .from('restaurants')
                                                    .select('*')
                                                            .eq('slug', restaurantSlug)
                                                                    .single()

                                                                          if (!rest) {
                                                                                  setNotFound(true)
                                                                                          setLoading(false)
                                                                                                  return
                                                                                                        }
                                                                                                              setRestaurant(rest)

                                                                                                                    const { data: cats } = await supabase
                                                                                                                            .from('menu_categories')
                                                                                                                                    .select('*')
                                                                                                                                            .eq('restaurant_id', rest.id)
                                                                                                                                                    .order('sort_order')

                                                                                                                                                          const { data: menuItems } = await supabase
                                                                                                                                                                  .from('menu_items')
                                                                                                                                                                          .select('*')
                                                                                                                                                                                  .eq('restaurant_id', rest.id)
                                                                                                                                                                                          .neq('availability', 'hidden')

                                                                                                                                                                                                setCategories(cats || [])
                                                                                                                                                                                                      setItems(menuItems || [])
                                                                                                                                                                                                            setLoading(false)
                                                                                                                                                                                                                }
                                                                                                                                                                                                                    load()
                                                                                                                                                                                                                      }, [restaurantSlug])

                                                                                                                                                                                                                        const tabCategories = useMemo(
                                                                                                                                                                                                                            () => categories.filter((c) => items.some((i) => i.category_id === c.id)),
                                                                                                                                                                                                                                [categories, items]
                                                                                                                                                                                                                                  )

                                                                                                                                                                                                                                    const sections = useMemo(() => {
                                                                                                                                                                                                                                        const q = search.trim().toLowerCase()
                                                                                                                                                                                                                                            const list = items
                                                                                                                                                                                                                                                  .filter(
                                                                                                                                                                                                                                                          (i) =>
                                                                                                                                                                                                                                                                    !q || i.name.toLowerCase().includes(q) || (i.description || '').toLowerCase().includes(q)
                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                .sort((a, b) => Number(!!b.is_featured) - Number(!!a.is_featured))

                                                                                                                                                                                                                                                                                    const groups: Section[] = categories
                                                                                                                                                                                                                                                                                          .filter((c) => activeCat === 'all' || c.id === activeCat)
                                                                                                                                                                                                                                                                                                .map((c) => ({ id: c.id, name: c.name, items: list.filter((i) => i.category_id === c.id) }))

                                                                                                                                                                                                                                                                                                    if (activeCat === 'all') {
                                                                                                                                                                                                                                                                                                          const rest = list.filter((i) => !i.category_id || !categories.some((c) => c.id === i.category_id))
                                                                                                                                                                                                                                                                                                                if (rest.length) groups.push({ id: 'other', name: 'More', items: rest })
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                        return groups.filter((g) => g.items.length > 0)
                                                                                                                                                                                                                                                                                                                          }, [items, categories, search, activeCat])

                                                                                                                                                                                                                                                                                                                            if (loading) return <div style={{ padding: 24, fontSize: 18 }}>Loading menu...</div>
                                                                                                                                                                                                                                                                                                                              if (notFound) return <div style={{ padding: 24, fontSize: 18 }}>Restaurant not found.</div>

                                                                                                                                                                                                                                                                                                                                const isClosed = restaurant?.status === 'closed'
                                                                                                                                                                                                                                                                                                                                  const accent = `color-mix(in srgb, ${restaurant?.primary_color || '#ea580c'} 80%, #1c0f08)`
                                                                                                                                                                                                                                                                                                                                    const qtyOf = (id: string) => cart.items.find((i) => i.id === id)?.quantity ?? 0

                                                                                                                                                                                                                                                                                                                                      function goToCheckout() {
                                                                                                                                                                                                                                                                                                                                          if (!restaurant) return
                                                                                                                                                                                                                                                                                                                                              sessionStorage.setItem('cart', JSON.stringify(cart.items))
                                                                                                                                                                                                                                                                                                                                                  sessionStorage.setItem('restaurantId', restaurant.id)
                                                                                                                                                                                                                                                                                                                                                      sessionStorage.setItem('restaurantSlug', restaurant.slug)
                                                                                                                                                                                                                                                                                                                                                          if (tableParam) sessionStorage.setItem('table', tableParam)
                                                                                                                                                                                                                                                                                                                                                              navigate(`/r/${restaurant.slug}/checkout`)
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ background: '#fbf6ef', minHeight: '100vh' }}>
                                                                                                                                                                                                                                                                                                                                                                            <div style={{ maxWidth: 1100, margin: '0 auto', paddingBottom: 120 }}>
                                                                                                                                                                                                                                                                                                                                                                                    <Hero restaurant={restaurant} table={tableParam} closed={isClosed} />

                                                                                                                                                                                                                                                                                                                                                                                            <SearchAndTabs
                                                                                                                                                                                                                                                                                                                                                                                                      categories={tabCategories}
                                                                                                                                                                                                                                                                                                                                                                                                                active={activeCat}
                                                                                                                                                                                                                                                                                                                                                                                                                          onSelect={setActiveCat}
                                                                                                                                                                                                                                                                                                                                                                                                                                    search={search}
                                                                                                                                                                                                                                                                                                                                                                                                                                              onSearch={setSearch}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        accent={accent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: '4px 16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {sections.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ textAlign: 'center', color: '#7c6a5e', fontSize: 17, marginTop: 40 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            No dishes found.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {sections.map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div key={s.id} style={{ marginBottom: 22 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2 style={{ margin: '14px 0 12px', fontSize: 22, fontWeight: 800, color: '#2b1b12' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {s.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: 'grid',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gridTemplateColumns: 'repeat(auto-fill, minmax(155px, 1fr))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gap: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {s.items.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <MenuItemCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                item={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    qty={qtyOf(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accent={accent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={isClosed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onAdd={() => cart.addItem({ id: item.id, name: item.name, price: Number(item.price) })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(q) => cart.updateQuantity(item.id, q)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <CartBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      count={cart.totalCount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subtotal={cart.subtotal}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accent={accent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={isClosed}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onOpen={goToCheckout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  