import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'

type Restaurant = {
  id: string
    name: string
      slug: string
        logo_url: string | null
          slogan: string | null
            primary_color: string | null
              secondary_color: string | null
                status: string
                  city: string | null
                  }
                  type Category = { id: string; name: string }
                  type MenuItem = {
                    id: string
                      category_id: string | null
                        name: string
                          description: string | null
                            price: number
                              availability: string
                              }

                              export default function RestaurantMenu() {
                                const { restaurantSlug } = useParams()
                                  const [restaurant, setRestaurant] = useState<Restaurant | null>(null)
                                    const [categories, setCategories] = useState<Category[]>([])
                                      const [items, setItems] = useState<MenuItem[]>([])
                                        const [loading, setLoading] = useState(true)
                                          const [notFound, setNotFound] = useState(false)

                                            useEffect(() => {
                                                async function load() {
                                                      const { data: rest } = await supabase
                                                              .from('restaurants')
                                                                      .select('*')
                                                                              .eq('slug', restaurantSlug)
                                                                                      .single()

                                                                                            if (!rest) {
                                                                                                    setNotFound(true)
                                                                                                            setLoading(false)
                                                                                                                    return
                                                                                                                          }
                                                                                                                                setRestaurant(rest)

                                                                                                                                      const { data: cats } = await supabase
                                                                                                                                              .from('menu_categories')
                                                                                                                                                      .select('*')
                                                                                                                                                              .eq('restaurant_id', rest.id)
                                                                                                                                                                      .order('sort_order')

                                                                                                                                                                            const { data: menuItems } = await supabase
                                                                                                                                                                                    .from('menu_items')
                                                                                                                                                                                            .select('*')
                                                                                                                                                                                                    .eq('restaurant_id', rest.id)
                                                                                                                                                                                                            .neq('availability', 'hidden')

                                                                                                                                                                                                                  setCategories(cats || [])
                                                                                                                                                                                                                        setItems(menuItems || [])
                                                                                                                                                                                                                              setLoading(false)
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                      load()
                                                                                                                                                                                                                                        }, [restaurantSlug])

                                                                                                                                                                                                                                          if (loading) return <div style={{ padding: 24 }}>Loading menu...</div>
                                                                                                                                                                                                                                            if (notFound) return <div style={{ padding: 24 }}>Restaurant not found.</div>

                                                                                                                                                                                                                                              const isClosed = restaurant?.status === 'closed'

                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                    <div style={{ maxWidth: 480, margin: '0 auto', paddingBottom: 60 }}>
                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                            background: restaurant?.primary_color || '#1a1a1a',
                                                                                                                                                                                                                                                                                      color: restaurant?.secondary_color || '#fff',
                                                                                                                                                                                                                                                                                                padding: 24,
                                                                                                                                                                                                                                                                                                          textAlign: 'center',
                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                {restaurant?.logo_url && (
                                                                                                                                                                                                                                                                                                                                          <img src={restaurant.logo_url} alt="" style={{ width: 64, height: 64, borderRadius: '50%' }} />
                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                          <h1 style={{ margin: '8px 0 0' }}>{restaurant?.name}</h1>
                                                                                                                                                                                                                                                                                                                                                                  {restaurant?.slogan && <p style={{ margin: 0 }}>{restaurant.slogan}</p>}
                                                                                                                                                                                                                                                                                                                                                                          {restaurant?.city && <p style={{ margin: 0, fontSize: 12 }}>{restaurant.city}</p>}
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                      {isClosed && (
                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ background: '#fee', color: '#900', padding: 12, textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                        Restaurant is currently closed.
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ padding: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                    {categories.length === 0 && <p>No menu items yet.</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                            {categories.map((cat) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      const catItems = items.filter((i) => i.category_id === cat.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (catItems.length === 0) return null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={cat.id} style={{ marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3 style={{ borderBottom: '2px solid #eee', paddingBottom: 4 }}>{cat.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {catItems.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '10px 0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderBottom: '1px solid #f0f0f0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          opacity: item.availability === 'sold_out' ? 0.5 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontWeight: 600 }}>{item.name}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.description && <div style={{ fontSize: 13, color: '#666' }}>{item.description}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {item.availability === 'sold_out' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontSize: 12, color: '#c00' }}>Sold out</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontWeight: 600 }}>₦{item.price}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                