import { useState } from 'react'
import { Card, Check, SaveBar, inputStyle } from './settingsKit'
import type { DayHours, SectionProps } from './settingsKit'

const DAYS: [string, string][] = [
  ['mon', 'Monday'],
    ['tue', 'Tuesday'],
      ['wed', 'Wednesday'],
        ['thu', 'Thursday'],
          ['fri', 'Friday'],
            ['sat', 'Saturday'],
              ['sun', 'Sunday'],
              ]
              const DEFAULT: DayHours = { closed: false, open: '09:00', close: '22:00' }

              export function HoursSection({ row, save }: SectionProps) {
                const [on, setOn] = useState(!!row.use_opening_hours)
                  const [hours, setHours] = useState<Record<string, DayHours>>(() => {
                      const start: Record<string, DayHours> = {}
                          for (const [k] of DAYS) start[k] = { ...DEFAULT, ...(row.opening_hours?.[k] ?? {}) }
                              return start
                                })

                                  const set = (k: string, patch: Partial<DayHours>) =>
                                      setHours((h) => ({ ...h, [k]: { ...h[k], ...patch } }))

                                        return (
                                            <Card
                                                  title="Opening hours"
                                                        hint="When on, customers can only order during these hours (Lagos time). A closing time after midnight is fine."
                                                            >
                                                                  <Check checked={on} onChange={setOn} label="Use opening hours" />
                                                                        {on &&
                                                                                DAYS.map(([k, label]) => (
                                                                                          <div key={k} style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10, flexWrap: 'wrap' }}>
                                                                                                      <strong style={{ width: 96, fontSize: 15 }}>{label}</strong>
                                                                                                                  <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 15 }}>
                                                                                                                                <input
                                                                                                                                                type="checkbox"
                                                                                                                                                                checked={hours[k].closed}
                                                                                                                                                                                onChange={(e) => set(k, { closed: e.target.checked })}
                                                                                                                                                                                                style={{ width: 20, height: 20 }}
                                                                                                                                                                                                              />
                                                                                                                                                                                                                            Closed
                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                    {!hours[k].closed && (
                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                    type="time"
                                                                                                                                                                                                                                                                                                                      value={hours[k].open}
                                                                                                                                                                                                                                                                                                                                        onChange={(e) => set(k, { open: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                          style={{ ...inputStyle, width: 120, padding: '8px 10px' }}
                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                          <span>to</span>
                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                            type="time"
                                                                                                                                                                                                                                                                                                                                                                                                                                              value={hours[k].close}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => set(k, { close: e.target.value })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ ...inputStyle, width: 120, padding: '8px 10px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SaveBar onSave={() => save({ use_opening_hours: on, opening_hours: hours })} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          