import { useEffect, useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'

type OrderItem = { id: string; item_name: string; quantity: number }
type Order = {
  id: string
    order_number: string
      status: string
        order_type: string
          total: number
            created_at: string
              table_id: string | null
              }

              const STAGES = [
                { key: 'confirmed', label: 'NEW', next: 'preparing', action: 'Start Preparing' },
                  { key: 'preparing', label: 'PREPARING', next: 'ready', action: 'Mark Ready' },
                    { key: 'ready', label: 'READY', next: 'completed', action: 'Mark Completed' },
                    ]

                    export default function Kitchen() {
                      const { profile } = useAuth()
                        const [orders, setOrders] = useState<Order[]>([])
                          const [itemsByOrder, setItemsByOrder] = useState<Record<string, OrderItem[]>>({})
                            const [tableNumbers, setTableNumbers] = useState<Record<string, string>>({})

                              async function loadOrders() {
                                  if (!profile?.restaurant_id) return

                                      const { data: orderRows } = await supabase
                                            .from('orders')
                                                  .select('id, order_number, status, order_type, total, created_at, table_id')
                                                        .eq('restaurant_id', profile.restaurant_id)
                                                              .in('status', ['confirmed', 'preparing', 'ready'])
                                                                    .order('created_at', { ascending: true })

                                                                        setOrders(orderRows || [])

                                                                            if (orderRows && orderRows.length > 0) {
                                                                                  const orderIds = orderRows.map((o) => o.id)
                                                                                        const { data: itemRows } = await supabase
                                                                                                .from('order_items')
                                                                                                        .select('id, order_id, item_name, quantity')
                                                                                                                .in('order_id', orderIds)

                                                                                                                      const grouped: Record<string, OrderItem[]> = {}
                                                                                                                            itemRows?.forEach((item: any) => {
                                                                                                                                    if (!grouped[item.order_id]) grouped[item.order_id] = []
                                                                                                                                            grouped[item.order_id].push(item)
                                                                                                                                                  })
                                                                                                                                                        setItemsByOrder(grouped)

                                                                                                                                                              const tableIds = [...new Set(orderRows.map((o) => o.table_id).filter(Boolean))]
                                                                                                                                                                    if (tableIds.length > 0) {
                                                                                                                                                                            const { data: tableRows } = await supabase
                                                                                                                                                                                      .from('tables')
                                                                                                                                                                                                .select('id, table_number')
                                                                                                                                                                                                          .in('id', tableIds as string[])
                                                                                                                                                                                                                  const tMap: Record<string, string> = {}
                                                                                                                                                                                                                          tableRows?.forEach((t) => { tMap[t.id] = t.table_number })
                                                                                                                                                                                                                                  setTableNumbers(tMap)
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                  setItemsByOrder({})
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                          useEffect(() => {
                                                                                                                                                                                                                                                              loadOrders()
                                                                                                                                                                                                                                                                  const interval = setInterval(loadOrders, 10000)
                                                                                                                                                                                                                                                                      return () => clearInterval(interval)
                                                                                                                                                                                                                                                                        }, [profile?.restaurant_id])

                                                                                                                                                                                                                                                                          async function advanceStatus(orderId: string, nextStatus: string) {
                                                                                                                                                                                                                                                                              const timestampField =
                                                                                                                                                                                                                                                                                    nextStatus === 'preparing' ? 'preparing_at' :
                                                                                                                                                                                                                                                                                          nextStatus === 'ready' ? 'ready_at' :
                                                                                                                                                                                                                                                                                                nextStatus === 'completed' ? 'completed_at' : null

                                                                                                                                                                                                                                                                                                    const update: Record<string, any> = { status: nextStatus }
                                                                                                                                                                                                                                                                                                        if (timestampField) update[timestampField] = new Date().toISOString()

                                                                                                                                                                                                                                                                                                            await supabase.from('orders').update(update).eq('id', orderId)
                                                                                                                                                                                                                                                                                                                loadOrders()
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                    const columns = STAGES.map((stage) => ({
                                                                                                                                                                                                                                                                                                                        ...stage,
                                                                                                                                                                                                                                                                                                                            orders: orders.filter((o) => o.status === stage.key),
                                                                                                                                                                                                                                                                                                                              }))

                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                          <h1>Kitchen</h1>
                                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                        {columns.map((col) => (
                                                                                                                                                                                                                                                                                                                                                                  <div key={col.key} style={{ flex: 1, minWidth: 280 }}>
                                                                                                                                                                                                                                                                                                                                                                              <h2 style={{ fontSize: 20 }}>{col.label} ({col.orders.length})</h2>
                                                                                                                                                                                                                                                                                                                                                                                          {col.orders.length === 0 && <p style={{ color: '#999' }}>No orders</p>}
                                                                                                                                                                                                                                                                                                                                                                                                      {col.orders.map((order) => (
                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                    key={order.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: '2px solid #333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: col.key === 'confirmed' ? '#fff3cd' : '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 20, fontWeight: 700 }}>#{order.order_number}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 14, color: '#555' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {order.order_type === 'dine_in' && order.table_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? `Table ${tableNumbers[order.table_id] || '?'}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      : order.order_type.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ul style={{ margin: '8px 0', paddingLeft: 20 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {(itemsByOrder[order.id] || []).map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li key={item.id} style={{ fontSize: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.item_name} × {item.quantity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontWeight: 700 }}>TOTAL ₦{order.total}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ color: 'green', fontSize: 13, marginBottom: 8 }}>PAYMENT VERIFIED ✓</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => advanceStatus(order.id, col.next)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: '100%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: '#1a1a1a',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {col.action}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        