import { useEffect, useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'

type Category = { id: string; name: string }
type MenuItem = {
  id: string
    category_id: string | null
      name: string
        description: string | null
          price: number
            availability: string
            }

            const inputStyle = { padding: 8, marginRight: 8, marginBottom: 8 }

            export default function Menu() {
              const { profile } = useAuth()
                const [categories, setCategories] = useState<Category[]>([])
                  const [items, setItems] = useState<MenuItem[]>([])
                    const [newCategoryName, setNewCategoryName] = useState('')
                      const [itemForms, setItemForms] = useState<Record<string, { name: string; price: string }>>({})
                        const [error, setError] = useState('')

                          async function loadData() {
                              if (!profile?.restaurant_id) return
                                  const { data: cats } = await supabase
                                        .from('menu_categories')
                                              .select('*')
                                                    .eq('restaurant_id', profile.restaurant_id)
                                                          .order('sort_order')
                                                              const { data: menuItems } = await supabase
                                                                    .from('menu_items')
                                                                          .select('*')
                                                                                .eq('restaurant_id', profile.restaurant_id)
                                                                                    setCategories(cats || [])
                                                                                        setItems(menuItems || [])
                                                                                          }

                                                                                            useEffect(() => {
                                                                                                loadData()
                                                                                                  }, [profile?.restaurant_id])

                                                                                                    async function addCategory() {
                                                                                                        setError('')
                                                                                                            if (!newCategoryName.trim()) return
                                                                                                                const { error } = await supabase.from('menu_categories').insert({
                                                                                                                      restaurant_id: profile?.restaurant_id,
                                                                                                                            name: newCategoryName,
                                                                                                                                })
                                                                                                                                    if (error) {
                                                                                                                                          setError(error.message)
                                                                                                                                                return
                                                                                                                                                    }
                                                                                                                                                        setNewCategoryName('')
                                                                                                                                                            loadData()
                                                                                                                                                              }

                                                                                                                                                                async function deleteCategory(id: string) {
                                                                                                                                                                    if (!confirm('Delete this category and its items?')) return
                                                                                                                                                                        await supabase.from('menu_categories').delete().eq('id', id)
                                                                                                                                                                            loadData()
                                                                                                                                                                              }

                                                                                                                                                                                async function addItem(categoryId: string) {
                                                                                                                                                                                    setError('')
                                                                                                                                                                                        const form = itemForms[categoryId]
                                                                                                                                                                                            if (!form?.name?.trim() || !form?.price?.trim()) return
                                                                                                                                                                                                const { error } = await supabase.from('menu_items').insert({
                                                                                                                                                                                                      restaurant_id: profile?.restaurant_id,
                                                                                                                                                                                                            category_id: categoryId,
                                                                                                                                                                                                                  name: form.name,
                                                                                                                                                                                                                        price: parseFloat(form.price) || 0,
                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                                                      setError(error.message)
                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    setItemForms({ ...itemForms, [categoryId]: { name: '', price: '' } })
                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            async function deleteItem(id: string) {
                                                                                                                                                                                                                                                                if (!confirm('Delete this item?')) return
                                                                                                                                                                                                                                                                    await supabase.from('menu_items').delete().eq('id', id)
                                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                            async function toggleAvailability(item: MenuItem) {
                                                                                                                                                                                                                                                                                const next = item.availability === 'available' ? 'sold_out' : 'available'
                                                                                                                                                                                                                                                                                    await supabase.from('menu_items').update({ availability: next }).eq('id', item.id)
                                                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                      <h1>Menu</h1>
                                                                                                                                                                                                                                                                                                            {error && <p style={{ color: 'red' }}>{error}</p>}

                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                    style={inputStyle}
                                                                                                                                                                                                                                                                                                                                              placeholder="New category name (e.g. Rice)"
                                                                                                                                                                                                                                                                                                                                                        value={newCategoryName}
                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setNewCategoryName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={addCategory}>+ Add Category</button>
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                              {categories.map((cat) => {
                                                                                                                                                                                                                                                                                                                                                                                                      const catItems = items.filter((i) => i.category_id === cat.id)
                                                                                                                                                                                                                                                                                                                                                                                                              const form = itemForms[cat.id] || { name: '', price: '' }
                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={cat.id} style={{ border: '1px solid #ccc', padding: 12, marginBottom: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>{cat.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => deleteCategory(cat.id)}>Delete Category</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {catItems.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={item.id} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '4px 0', borderBottom: '1px solid #eee' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{item.name} — ₦{item.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => toggleAvailability(item)} style={{ marginRight: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {item.availability === 'available' ? 'Mark Sold Out' : 'Mark Available'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => deleteItem(item.id)}>Delete</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginTop: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Item name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={form.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setItemForms({ ...itemForms, [cat.id]: { ...form, name: e.target.value } })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Price"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={form.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setItemForms({ ...itemForms, [cat.id]: { ...form, price: e.target.value } })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => addItem(cat.id)}>+ Add Item</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              