import { useEffect, useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'
import { MenuItemRow } from './MenuItemRow'
import type { DashItem } from './MenuItemRow'

type Category = { id: string; name: string }

const inputStyle = {
  padding: '10px 12px',
    fontSize: 16,
      borderRadius: 8,
        border: '1.5px solid #d6cdc4',
          marginRight: 8,
            marginBottom: 8,
            } as const

            const primaryBtn = {
              padding: '10px 16px',
                fontSize: 16,
                  fontWeight: 700,
                    borderRadius: 8,
                      border: 'none',
                        background: '#ea580c',
                          color: '#fff',
                            cursor: 'pointer',
                            } as const

                            export default function Menu() {
                              const { profile } = useAuth()
                                const [categories, setCategories] = useState<Category[]>([])
                                  const [items, setItems] = useState<DashItem[]>([])
                                    const [newCategoryName, setNewCategoryName] = useState('')
                                      const [itemForms, setItemForms] = useState<Record<string, { name: string; price: string }>>({})
                                        const [error, setError] = useState('')

                                          async function loadData() {
                                              if (!profile?.restaurant_id) return
                                                  const { data: cats } = await supabase
                                                        .from('menu_categories')
                                                              .select('*')
                                                                    .eq('restaurant_id', profile.restaurant_id)
                                                                          .order('sort_order')
                                                                              const { data: menuItems } = await supabase
                                                                                    .from('menu_items')
                                                                                          .select('*')
                                                                                                .eq('restaurant_id', profile.restaurant_id)
                                                                                                    setCategories(cats || [])
                                                                                                        setItems(menuItems || [])
                                                                                                          }

                                                                                                            useEffect(() => {
                                                                                                                loadData()
                                                                                                                  }, [profile?.restaurant_id])

                                                                                                                    async function addCategory() {
                                                                                                                        setError('')
                                                                                                                            if (!newCategoryName.trim()) return
                                                                                                                                const { error } = await supabase.from('menu_categories').insert({
                                                                                                                                      restaurant_id: profile?.restaurant_id,
                                                                                                                                            name: newCategoryName,
                                                                                                                                                })
                                                                                                                                                    if (error) {
                                                                                                                                                          setError(error.message)
                                                                                                                                                                return
                                                                                                                                                                    }
                                                                                                                                                                        setNewCategoryName('')
                                                                                                                                                                            loadData()
                                                                                                                                                                              }

                                                                                                                                                                                async function deleteCategory(id: string) {
                                                                                                                                                                                    if (!confirm('Delete this category and its items?')) return
                                                                                                                                                                                        await supabase.from('menu_categories').delete().eq('id', id)
                                                                                                                                                                                            loadData()
                                                                                                                                                                                              }

                                                                                                                                                                                                async function addItem(categoryId: string) {
                                                                                                                                                                                                    setError('')
                                                                                                                                                                                                        const form = itemForms[categoryId]
                                                                                                                                                                                                            if (!form?.name?.trim() || !form?.price?.trim()) return
                                                                                                                                                                                                                const { error } = await supabase.from('menu_items').insert({
                                                                                                                                                                                                                      restaurant_id: profile?.restaurant_id,
                                                                                                                                                                                                                            category_id: categoryId,
                                                                                                                                                                                                                                  name: form.name,
                                                                                                                                                                                                                                        price: parseFloat(form.price) || 0,
                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                                                                      setError(error.message)
                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    setItemForms({ ...itemForms, [categoryId]: { name: '', price: '' } })
                                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                            async function deleteItem(id: string) {
                                                                                                                                                                                                                                                                                if (!confirm('Delete this item?')) return
                                                                                                                                                                                                                                                                                    await supabase.from('menu_items').delete().eq('id', id)
                                                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                            async function toggleAvailability(item: DashItem) {
                                                                                                                                                                                                                                                                                                const next = item.availability === 'available' ? 'sold_out' : 'available'
                                                                                                                                                                                                                                                                                                    await supabase.from('menu_items').update({ availability: next }).eq('id', item.id)
                                                                                                                                                                                                                                                                                                        loadData()
                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                <div style={{ padding: 16, maxWidth: 900 }}>
                                                                                                                                                                                                                                                                                                                      <h1>Menu</h1>
                                                                                                                                                                                                                                                                                                                            {error && <p style={{ color: '#b91c1c' }}>{error}</p>}

                                                                                                                                                                                                                                                                                                                                  <div style={{ marginBottom: 20 }}>
                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                    style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                              placeholder="New category (e.g. Rice)"
                                                                                                                                                                                                                                                                                                                                                                        value={newCategoryName}
                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setNewCategoryName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                  <button style={primaryBtn} onClick={addCategory}>
                                                                                                                                                                                                                                                                                                                                                                                                            + Add Category
                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                {categories.map((cat) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const catItems = items.filter((i) => i.category_id === cat.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                const form = itemForms[cat.id] || { name: '', price: '' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              key={cat.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        background: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 style={{ margin: 0 }}>{cat.name}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => deleteCategory(cat.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ border: 'none', background: 'transparent', color: '#b91c1c', fontSize: 15 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Delete category
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {catItems.length === 0 && <p style={{ color: '#7c6a5e' }}>No items yet.</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {catItems.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <MenuItemRow
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            item={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            restaurantId={profile?.restaurant_id || ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChanged={loadData}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onToggle={() => toggleAvailability(item)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onDelete={() => deleteItem(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onError={setError}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ marginTop: 12, display: 'flex', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Item name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={form.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setItemForms({ ...itemForms, [cat.id]: { ...form, name: e.target.value } })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ ...inputStyle, width: 110 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Price"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              inputMode="decimal"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={form.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setItemForms({ ...itemForms, [cat.id]: { ...form, price: e.target.value } })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button style={primaryBtn} onClick={() => addItem(cat.id)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            + Add Item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    