import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'
import { loadFeed, timeAgo } from './feed/notifyFeed'
import type { Group, Notice } from './feed/notifyFeed'

const SEEN_KEY = 'notif_seen_at'
const FILTERS: { key: 'all' | Group; label: string }[] = [
  { key: 'all', label: 'All' },
    { key: 'orders', label: 'Orders' },
      { key: 'payments', label: 'Payments' },
        { key: 'rewards', label: 'Rewards' },
        ]

        export default function Notifications() {
          const { profile } = useAuth()
            const rid = profile?.restaurant_id
              const [notices, setNotices] = useState<Notice[]>([])
                const [waiting, setWaiting] = useState(0)
                  const [filter, setFilter] = useState<'all' | Group>('all')
                    const [seenAt, setSeenAt] = useState(() => localStorage.getItem(SEEN_KEY) || '1970-01-01T00:00:00Z')
                      const [error, setError] = useState('')
                        const [loading, setLoading] = useState(true)

                          const load = useCallback(async () => {
                              if (!rid) return
                                  try {
                                        const f = await loadFeed(rid)
                                              setNotices(f.notices)
                                                    setWaiting(f.waiting)
                                                          setError('')
                                                              } catch (e) {
                                                                    setError(e instanceof Error ? e.message : 'Could not load notifications')
                                                                        }
                                                                            setLoading(false)
                                                                              }, [rid])

                                                                                useEffect(() => {
                                                                                    load()
                                                                                        if (!rid) return
                                                                                            const channel = supabase
                                                                                                  .channel(`notif-${rid}`)
                                                                                                        .on(
                                                                                                                'postgres_changes',
                                                                                                                        { event: '*', schema: 'public', table: 'orders', filter: `restaurant_id=eq.${rid}` },
                                                                                                                                () => load()
                                                                                                                                      )
                                                                                                                                            .subscribe()
                                                                                                                                                const timer = setInterval(load, 60000)
                                                                                                                                                    return () => {
                                                                                                                                                          supabase.removeChannel(channel)
                                                                                                                                                                clearInterval(timer)
                                                                                                                                                                    }
                                                                                                                                                                      }, [rid, load])

                                                                                                                                                                        // Anything you saw on this page counts as read when you leave
                                                                                                                                                                          useEffect(
                                                                                                                                                                              () => () => {
                                                                                                                                                                                    localStorage.setItem(SEEN_KEY, new Date().toISOString())
                                                                                                                                                                                        },
                                                                                                                                                                                            []
                                                                                                                                                                                              )

                                                                                                                                                                                                function markAllRead() {
                                                                                                                                                                                                    const now = new Date().toISOString()
                                                                                                                                                                                                        localStorage.setItem(SEEN_KEY, now)
                                                                                                                                                                                                            setSeenAt(now)
                                                                                                                                                                                                              }

                                                                                                                                                                                                                const shown = notices.filter((n) => filter === 'all' || n.group === filter)
                                                                                                                                                                                                                  const unread = notices.filter((n) => n.at > seenAt).length

                                                                                                                                                                                                                    if (error) return <div style={{ padding: 24, color: '#b91c1c' }}>{error}</div>

                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                          <div style={{ padding: 16, maxWidth: 720 }}>
                                                                                                                                                                                                                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                        <h1 style={{ margin: 0 }}>
                                                                                                                                                                                                                                                  Notifications
                                                                                                                                                                                                                                                            {unread > 0 && (
                                                                                                                                                                                                                                                                        <span style={{ marginLeft: 10, background: '#dc2626', color: '#fff', borderRadius: 12, fontSize: 14, padding: '2px 10px', verticalAlign: 'middle' }}>
                                                                                                                                                                                                                                                                                      {unread} new
                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                    </h1>
                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                      onClick={markAllRead}
                                                                                                                                                                                                                                                                                                                                                disabled={unread === 0}
                                                                                                                                                                                                                                                                                                                                                          style={{ padding: '9px 14px', fontSize: 15, borderRadius: 10, border: '1.5px solid #d9d9d9', background: '#fff' }}
                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                            Mark all as read
                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                {waiting > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                        <Link
                                                                                                                                                                                                                                                                                                                                                                                                                  to="/dashboard/kitchen"
                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ display: 'block', margin: '12px 0', background: '#dc2626', color: '#fff', borderRadius: 14, padding: '12px 14px', fontWeight: 800, fontSize: 17, textDecoration: 'none' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                              🚨 {waiting} order{waiting > 1 ? 's' : ''} waiting to be accepted. Open Kitchen →
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', gap: 8, margin: '12px 0', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {FILTERS.map((f) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={f.key}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => setFilter(f.key)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: '8px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: filter === f.key ? '#2b1b12' : '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: filter === f.key ? '#fff' : '#2b1b12',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {f.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading && <p>Loading...</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!loading && shown.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ color: '#6b6b6b', fontSize: 16 }}>Nothing here yet. New orders and activity from the last 7 days will show up here.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'grid', gap: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {shown.map((n) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const isNew = n.at > seenAt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key={n.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      gap: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: isNew ? '#fff7ed' : '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: '12px 14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderLeft: isNew ? '4px solid #ea580c' : '4px solid transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 26 }}>{n.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ flex: 1, minWidth: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 16, fontWeight: 700 }}>{n.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 14, color: '#6b6b6b' }}>{n.detail}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: 13, color: '#6b6b6b', whiteSpace: 'nowrap' }}>{timeAgo(n.at)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }