import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'

type Restaurant = { id: string; slug: string; name: string }
type TableRow = { id: string; table_number: string }

const PUBLIC_URL = (import.meta.env.VITE_PUBLIC_URL as string | undefined)?.replace(/\/$/, '')

function downloadQR(svgId: string, filename: string) {
  const svg = document.getElementById(svgId)
    if (!svg) return
      const svgData = new XMLSerializer().serializeToString(svg)
        const canvas = document.createElement('canvas')
          canvas.width = 512
            canvas.height = 512
              const ctx = canvas.getContext('2d')
                const img = new Image()
                  img.onload = () => {
                      if (!ctx) return
                          ctx.fillStyle = '#ffffff'
                              ctx.fillRect(0, 0, 512, 512)
                                  ctx.drawImage(img, 32, 32, 448, 448)
                                      const a = document.createElement('a')
                                          a.href = canvas.toDataURL('image/png')
                                              a.download = filename
                                                  a.click()
                                                    }
                                                      img.src = 'data:image/svg+xml;base64,' + btoa(svgData)
                                                      }

                                                      function QrCard(p: { id: string; name: string; title: string; subtitle: string; url: string; file: string }) {
                                                        return (
                                                            <div
                                                                  style={{
                                                                          background: '#fff',
                                                                                  borderRadius: 16,
                                                                                          padding: 16,
                                                                                                  textAlign: 'center',
                                                                                                          boxShadow: '0 1px 4px rgba(0,0,0,0.1)',
                                                                                                                  breakInside: 'avoid',
                                                                                                                        }}
                                                                                                                            >
                                                                                                                                  <div style={{ fontSize: 15, color: '#6b6b6b' }}>{p.name}</div>
                                                                                                                                        <div style={{ fontSize: 26, fontWeight: 800, margin: '2px 0 10px' }}>{p.title}</div>
                                                                                                                                              <QRCodeSVG id={p.id} value={p.url} size={170} />
                                                                                                                                                    <div style={{ fontSize: 14, margin: '10px 0 4px' }}>{p.subtitle}</div>
                                                                                                                                                          <div style={{ fontSize: 11, color: '#999', wordBreak: 'break-all' }}>{p.url}</div>
                                                                                                                                                                <button
                                                                                                                                                                        className="no-print"
                                                                                                                                                                                onClick={() => downloadQR(p.id, p.file)}
                                                                                                                                                                                        style={{ marginTop: 10, padding: '8px 14px', fontSize: 14, borderRadius: 8, border: '1.5px solid #d9d9d9', background: '#fff' }}
                                                                                                                                                                                              >
                                                                                                                                                                                                      Download PNG
                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                  )
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                  export default function QRManagement() {
                                                                                                                                                                                                                    const { profile } = useAuth()
                                                                                                                                                                                                                      const [restaurant, setRestaurant] = useState<Restaurant | null>(null)
                                                                                                                                                                                                                        const [tables, setTables] = useState<TableRow[]>([])
                                                                                                                                                                                                                          const baseUrl = PUBLIC_URL || window.location.origin

                                                                                                                                                                                                                            useEffect(() => {
                                                                                                                                                                                                                                async function load() {
                                                                                                                                                                                                                                      if (!profile?.restaurant_id) return
                                                                                                                                                                                                                                            const { data: rest } = await supabase
                                                                                                                                                                                                                                                    .from('restaurants')
                                                                                                                                                                                                                                                            .select('id, slug, name')
                                                                                                                                                                                                                                                                    .eq('id', profile.restaurant_id)
                                                                                                                                                                                                                                                                            .single()
                                                                                                                                                                                                                                                                                  setRestaurant(rest)
                                                                                                                                                                                                                                                                                        const { data: rows } = await supabase
                                                                                                                                                                                                                                                                                                .from('tables')
                                                                                                                                                                                                                                                                                                        .select('id, table_number')
                                                                                                                                                                                                                                                                                                                .eq('restaurant_id', profile.restaurant_id)
                                                                                                                                                                                                                                                                                                                      const list = (rows ?? []) as TableRow[]
                                                                                                                                                                                                                                                                                                                            setTables(list.sort((a, b) => a.table_number.localeCompare(b.table_number, undefined, { numeric: true })))
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    load()
                                                                                                                                                                                                                                                                                                                                      }, [profile?.restaurant_id])

                                                                                                                                                                                                                                                                                                                                        if (!restaurant) return <div style={{ padding: 24 }}>Loading...</div>

                                                                                                                                                                                                                                                                                                                                          const restaurantUrl = `${baseUrl}/r/${restaurant.slug}`
                                                                                                                                                                                                                                                                                                                                            const temporary = /github\.dev|localhost|127\.0\.0\.1/.test(baseUrl)

                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                  <div style={{ padding: 16, maxWidth: 1000 }}>
                                                                                                                                                                                                                                                                                                                                                        <style>{'@media print{aside,header,.no-print{display:none!important}}'}</style>

                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                      <h1 style={{ margin: 0 }}>Tables & QR</h1>
                                                                                                                                                                                                                                                                                                                                                                              <div className="no-print" style={{ display: 'flex', gap: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/dashboard/settings" style={{ padding: '10px 14px', border: '1.5px solid #d9d9d9', borderRadius: 10, background: '#fff', textDecoration: 'none', color: '#2b1b12' }}>
                                                                                                                                                                                                                                                                                                                                                                                                    Manage tables
                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => window.print()} style={{ padding: '10px 14px', border: 'none', borderRadius: 10, background: '#2b1b12', color: '#fff', fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                    🖨 Print all
                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {temporary && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="no-print" style={{ background: '#fef2f2', color: '#991b1b', borderRadius: 12, padding: 12, margin: '12px 0', fontSize: 15 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ⚠️ These QR codes point to a temporary address ({baseUrl}). Open this page on your live website before printing.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 14, marginTop: 14 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <QrCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id="qr-restaurant"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name={restaurant.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title="Menu"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subtitle="Scan to view the menu and order"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  url={restaurantUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            file={`${restaurant.slug}-menu-qr.png`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {tables.map((t) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <QrCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={t.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id={`qr-table-${t.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name={restaurant.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title={`Table ${t.table_number}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  subtitle="Scan to view the menu and order"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              url={`${restaurantUrl}?table=${encodeURIComponent(t.table_number)}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          file={`table-${t.table_number}-qr.png`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {tables.length === 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p style={{ marginTop: 20, fontSize: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          No tables yet. Go to <Link to="/dashboard/settings">Settings → Tables and QR codes</Link> to create them.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              