import { useEffect, useState } from 'react'
import { QRCodeSVG } from 'qrcode.react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'

type Restaurant = { id: string; slug: string; name: string }
type TableRow = { id: string; table_number: string }

export default function QRManagement() {
  const { profile } = useAuth()
    const [restaurant, setRestaurant] = useState<Restaurant | null>(null)
      const [tables, setTables] = useState<TableRow[]>([])

        const baseUrl = window.location.origin

          useEffect(() => {
              async function load() {
                    if (!profile?.restaurant_id) return
                          const { data: rest } = await supabase
                                  .from('restaurants')
                                          .select('id, slug, name')
                                                  .eq('id', profile.restaurant_id)
                                                          .single()
                                                                setRestaurant(rest)

                                                                      const { data: tableRows } = await supabase
                                                                              .from('tables')
                                                                                      .select('id, table_number')
                                                                                              .eq('restaurant_id', profile.restaurant_id)
                                                                                                      .order('table_number')
                                                                                                            setTables(tableRows || [])
                                                                                                                }
                                                                                                                    load()
                                                                                                                      }, [profile?.restaurant_id])

                                                                                                                        function downloadQR(svgId: string, filename: string) {
                                                                                                                            const svg = document.getElementById(svgId)
                                                                                                                                if (!svg) return
                                                                                                                                    const svgData = new XMLSerializer().serializeToString(svg)
                                                                                                                                        const canvas = document.createElement('canvas')
                                                                                                                                            canvas.width = 512
                                                                                                                                                canvas.height = 512
                                                                                                                                                    const ctx = canvas.getContext('2d')
                                                                                                                                                        const img = new Image()
                                                                                                                                                            img.onload = () => {
                                                                                                                                                                  ctx?.drawImage(img, 0, 0, 512, 512)
                                                                                                                                                                        const pngUrl = canvas.toDataURL('image/png')
                                                                                                                                                                              const a = document.createElement('a')
                                                                                                                                                                                    a.href = pngUrl
                                                                                                                                                                                          a.download = filename
                                                                                                                                                                                                a.click()
                                                                                                                                                                                                    }
                                                                                                                                                                                                        img.src = 'data:image/svg+xml;base64,' + btoa(svgData)
                                                                                                                                                                                                          }

                                                                                                                                                                                                            if (!restaurant) return <div>Loading...</div>

                                                                                                                                                                                                              const restaurantUrl = `${baseUrl}/r/${restaurant.slug}`

                                                                                                                                                                                                                return (
                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                          <h1>QR Management</h1>

                                                                                                                                                                                                                                <div style={{ border: '1px solid #ccc', padding: 16, marginBottom: 24, maxWidth: 320 }}>
                                                                                                                                                                                                                                        <h3>Restaurant QR</h3>
                                                                                                                                                                                                                                                <p style={{ fontSize: 13, wordBreak: 'break-all' }}>{restaurantUrl}</p>
                                                                                                                                                                                                                                                        <QRCodeSVG id="qr-restaurant" value={restaurantUrl} size={200} />
                                                                                                                                                                                                                                                                <div style={{ marginTop: 8 }}>
                                                                                                                                                                                                                                                                          <button onClick={() => downloadQR('qr-restaurant', `${restaurant.slug}-qr.png`)}>
                                                                                                                                                                                                                                                                                      Download QR
                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                    <h3>Table QR Codes</h3>
                                                                                                                                                                                                                                                                                                                          {tables.length === 0 && <p>No tables yet — add tables in a future step.</p>}
                                                                                                                                                                                                                                                                                                                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16 }}>
                                                                                                                                                                                                                                                                                                                                        {tables.map((table) => {
                                                                                                                                                                                                                                                                                                                                                  const tableUrl = `${restaurantUrl}?table=${table.table_number}`
                                                                                                                                                                                                                                                                                                                                                            const svgId = `qr-table-${table.id}`
                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                  <div key={table.id} style={{ border: '1px solid #ccc', padding: 12, width: 220 }}>
                                                                                                                                                                                                                                                                                                                                                                                                <strong>Table {table.table_number}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                              <p style={{ fontSize: 11, wordBreak: 'break-all' }}>{tableUrl}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            <QRCodeSVG id={svgId} value={tableUrl} size={150} />
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginTop: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => downloadQR(svgId, `table-${table.table_number}-qr.png`)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Download
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    