import { useEffect, useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { RANGES, loadReport } from './reports/reportData'
import type { RangeKey, Report } from './reports/reportData'
import { BarList, COLORS, Kpi, Panel, naira } from './reports/reportParts'
import { HoursChart, RevenueChart, TypeDonut } from './reports/ReportCharts'

function exportCsv(r: Report, range: string) {
  const rows: (string | number)[][] = [
      ['Period', range],
          ['Revenue', r.revenue],
              ['Paid orders', r.orders],
                  ['Average order', Math.round(r.aov)],
                      [],
                          ['Day / hour', 'Revenue', 'Orders'],
                              ...r.trend.map((t) => [t.label, t.revenue, t.orders]),
                                  [],
                                      ['Dish', 'Sold', 'Revenue'],
                                          ...r.top.map((t) => [t.name, t.qty, t.revenue]),
                                            ]
                                              const csv = rows.map((row) => row.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n')
                                                const a = document.createElement('a')
                                                  a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
                                                    a.download = `report-${range}.csv`
                                                      a.click()
                                                        setTimeout(() => URL.revokeObjectURL(a.href), 1000)
                                                        }

                                                        export default function Reports() {
                                                          const { profile } = useAuth()
                                                            const [range, setRange] = useState<RangeKey>('7d')
                                                              const [r, setR] = useState<Report | null>(null)
                                                                const [error, setError] = useState('')
                                                                  const [loading, setLoading] = useState(true)

                                                                    useEffect(() => {
                                                                        if (!profile?.restaurant_id) return
                                                                            let alive = true
                                                                                setLoading(true)
                                                                                    loadReport(profile.restaurant_id, range)
                                                                                          .then((d) => {
                                                                                                  if (alive) {
                                                                                                            setR(d)
                                                                                                                      setError('')
                                                                                                                              }
                                                                                                                                    })
                                                                                                                                          .catch((e: Error) => {
                                                                                                                                                  if (alive) setError(e.message)
                                                                                                                                                        })
                                                                                                                                                              .finally(() => {
                                                                                                                                                                      if (alive) setLoading(false)
                                                                                                                                                                            })
                                                                                                                                                                                return () => {
                                                                                                                                                                                      alive = false
                                                                                                                                                                                          }
                                                                                                                                                                                            }, [profile?.restaurant_id, range])

                                                                                                                                                                                              if (error) return <div style={{ padding: 24, color: '#b91c1c' }}>{error}</div>
                                                                                                                                                                                                if (!r) return <div style={{ padding: 24 }}>Loading reports...</div>

                                                                                                                                                                                                  const grid = { display: 'grid', gap: 14, gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))' } as const
                                                                                                                                                                                                    const chip = { background: '#fff', borderRadius: 20, padding: '6px 12px', fontSize: 14, boxShadow: '0 1px 3px rgba(0,0,0,0.08)' } as const

                                                                                                                                                                                                      return (
                                                                                                                                                                                                          <div style={{ padding: 16, maxWidth: 1100, opacity: loading ? 0.6 : 1 }}>
                                                                                                                                                                                                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 }}>
                                                                                                                                                                                                                        <h1 style={{ margin: 0 }}>Reports</h1>
                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                          onClick={() => exportCsv(r, range)}
                                                                                                                                                                                                                                                    style={{ padding: '9px 14px', fontSize: 15, borderRadius: 10, border: '1.5px solid #d9d9d9', background: '#fff' }}
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                      ⬇ Export CSV
                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                          <div style={{ display: 'flex', gap: 8, margin: '12px 0', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                  {RANGES.map((x) => (
                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                        key={x.key}
                                                                                                                                                                                                                                                                                                                                    onClick={() => setRange(x.key)}
                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                              padding: '9px 16px',
                                                                                                                                                                                                                                                                                                                                                                            fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                      border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                    background: range === x.key ? '#2b1b12' : '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: range === x.key ? '#fff' : '#2b1b12',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {x.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ ...grid, gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Kpi label="Revenue" value={naira(r.revenue)} delta={r.dRevenue} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Kpi label="Paid orders" value={String(r.orders)} delta={r.dOrders} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Kpi label="Average order" value={naira(r.aov)} delta={r.dAov} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Kpi label="Customers" value={String(r.customers)} note={`${r.repeat} came back more than once`} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', margin: '12px 0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={chip}>⏰ Busiest hour: <strong>{r.peakHour}</strong></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={chip}>📅 Best day: <strong>{r.bestDay}</strong></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={chip}>✅ Payment completed: <strong>{r.conversion.toFixed(0)}%</strong></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span style={chip}>🎁 Rewards used: <strong>{r.rewards}</strong> ({naira(r.discounts)})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gap: 14 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Panel title="Revenue" sub={range === 'today' ? 'By hour, today' : 'By day'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <RevenueChart data={r.trend} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Panel>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={grid}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Panel title="Busiest hours" sub="Paid orders by time of day">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <HoursChart data={r.hours} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Panel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Panel title="Order types">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TypeDonut data={r.types} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Panel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Panel title="Top dishes" sub="By revenue">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <BarList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color={COLORS[0]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rows={r.top.map((t) => ({ name: t.name, value: t.revenue, label: `${naira(t.revenue)} · ${t.qty} sold` }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Panel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Panel title="Order progress">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <BarList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color={COLORS[2]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rows={r.statuses.map((s) => ({ name: s.name, value: s.value, label: String(s.value) }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Panel>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              