import { useEffect, useState, useCallback } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'

type OrderLite = {
  total: number
    status: string
      payment_status: string
        order_type: string
          created_at: string
          }

          const RANGE_OPTIONS = [
            { key: 'today', label: 'Today' },
              { key: '7d', label: 'Last 7 days' },
                { key: '30d', label: 'Last 30 days' },
                  { key: 'all', label: 'All time' },
                  ]

                  function rangeStart(key: string): string | null {
                    const d = new Date()
                      if (key === 'today') {
                          d.setHours(0, 0, 0, 0)
                              return d.toISOString()
                                }
                                  if (key === '7d') {
                                      d.setDate(d.getDate() - 7)
                                          return d.toISOString()
                                            }
                                              if (key === '30d') {
                                                  d.setDate(d.getDate() - 30)
                                                      return d.toISOString()
                                                        }
                                                          return null
                                                          }

                                                          export default function Reports() {
                                                            const { profile } = useAuth()
                                                              const restaurantId = profile?.restaurant_id

                                                                const [range, setRange] = useState('7d')
                                                                  const [orders, setOrders] = useState<OrderLite[]>([])
                                                                    const [loading, setLoading] = useState(true)
                                                                      const [error, setError] = useState('')

                                                                        const load = useCallback(async () => {
                                                                            if (!restaurantId) return
                                                                                setLoading(true)
                                                                                    setError('')

                                                                                        let query = supabase
                                                                                              .from('orders')
                                                                                                    .select('total, status, payment_status, order_type, created_at')
                                                                                                          .eq('restaurant_id', restaurantId)

                                                                                                              const start = rangeStart(range)
                                                                                                                  if (start) query = query.gte('created_at', start)

                                                                                                                      const { data, error: err } = await query

                                                                                                                          if (err) {
                                                                                                                                setError(err.message)
                                                                                                                                      setLoading(false)
                                                                                                                                            return
                                                                                                                                                }

                                                                                                                                                    setOrders((data || []) as OrderLite[])
                                                                                                                                                        setLoading(false)
                                                                                                                                                          }, [restaurantId, range])

                                                                                                                                                            useEffect(() => {
                                                                                                                                                                load()
                                                                                                                                                                  }, [load])

                                                                                                                                                                    const paid = orders.filter((o) => o.payment_status === 'success')
                                                                                                                                                                      const revenue = paid.reduce((s, o) => s + Number(o.total), 0)
                                                                                                                                                                        const orderCount = paid.length
                                                                                                                                                                          const avgOrder = orderCount > 0 ? revenue / orderCount : 0

                                                                                                                                                                            const byType: Record<string, number> = {}
                                                                                                                                                                              paid.forEach((o) => {
                                                                                                                                                                                  byType[o.order_type] = (byType[o.order_type] || 0) + 1
                                                                                                                                                                                    })

                                                                                                                                                                                      const byStatus: Record<string, number> = {}
                                                                                                                                                                                        orders.forEach((o) => {
                                                                                                                                                                                            byStatus[o.status] = (byStatus[o.status] || 0) + 1
                                                                                                                                                                                              })

                                                                                                                                                                                                if (!restaurantId) {
                                                                                                                                                                                                    return <div style={{ padding: 24 }}>Loading your restaurant...</div>
                                                                                                                                                                                                      }

                                                                                                                                                                                                        return (
                                                                                                                                                                                                            <div style={{ padding: 16 }}>
                                                                                                                                                                                                                  <h2>Reports</h2>

                                                                                                                                                                                                                        <div style={{ marginBottom: 16 }}>
                                                                                                                                                                                                                                <select value={range} onChange={(e) => setRange(e.target.value)} style={{ padding: 8 }}>
                                                                                                                                                                                                                                          {RANGE_OPTIONS.map((r) => (
                                                                                                                                                                                                                                                      <option key={r.key} value={r.key}>
                                                                                                                                                                                                                                                                    {r.label}
                                                                                                                                                                                                                                                                                </option>
                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                              {error && <p style={{ color: 'red' }}>{error}</p>}
                                                                                                                                                                                                                                                                                                                    {loading && <p>Loading...</p>}

                                                                                                                                                                                                                                                                                                                          {!loading && (
                                                                                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                                        <div style={{ background: '#f7f7f7', padding: 16, borderRadius: 8, flex: '1 1 140px' }}>
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 13, color: '#666' }}>Revenue</div>
                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: 22, fontWeight: 700 }}>₦{revenue.toLocaleString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ background: '#f7f7f7', padding: 16, borderRadius: 8, flex: '1 1 140px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontSize: 13, color: '#666' }}>Paid orders</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: 22, fontWeight: 700 }}>{orderCount}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ background: '#f7f7f7', padding: 16, borderRadius: 8, flex: '1 1 140px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 13, color: '#666' }}>Average order</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 22, fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ₦{avgOrder.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Orders by type</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {Object.entries(byType).length === 0 && <p>No paid orders in this range.</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {Object.entries(byType).map(([type, count]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={type} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ textTransform: 'capitalize' }}>{type.replace('_', ' ')}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>{count}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 style={{ marginTop: 20 }}>Orders by status</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {Object.entries(byStatus).map(([s, count]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={s} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ textTransform: 'capitalize' }}>{s}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{count}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  