import { useState } from 'react'
import { ringOnce, unlockAudio } from '../../hooks/orderRing'
import { BACKGROUND_PATTERNS } from '../../lib/backgroundPatterns'
import type { BackgroundKey } from '../../lib/backgroundPatterns'
import { Card, Field, SaveBar, inputStyle } from './settingsKit'
import type { SectionProps } from './settingsKit'

const REPEATS = [3, 4, 5, 10, 15, 30]
const MAX_RINGS = [0, 5, 10, 20, 50]

export function AlertsSection({ row, save }: SectionProps) {
  const [repeat, setRepeat] = useState(row.alert_repeat_seconds ?? 4)
    const [maxRings, setMaxRings] = useState(row.alert_max_rings ?? 0)
      const [style, setStyle] = useState(row.alert_style ?? 'phone')

        return (
            <Card
                  title="Order alerts"
                        hint="How the ring behaves when a new paid order arrives. Volume is set on the device itself."
                            >
                                  <Field label="Repeat the ring every">
                                          <select style={inputStyle} value={repeat} onChange={(e) => setRepeat(Number(e.target.value))}>
                                                    {REPEATS.map((s) => (
                                                                <option key={s} value={s}>
                                                                              {s} seconds
                                                                                          </option>
                                                                                                    ))}
                                                                                                            </select>
                                                                                                                  </Field>
                                                                                                                        <Field label="Keep ringing">
                                                                                                                                <select style={inputStyle} value={maxRings} onChange={(e) => setMaxRings(Number(e.target.value))}>
                                                                                                                                          {MAX_RINGS.map((n) => (
                                                                                                                                                      <option key={n} value={n}>
                                                                                                                                                                    {n === 0 ? 'Until the order is accepted' : `Stop after ${n} rings`}
                                                                                                                                                                                </option>
                                                                                                                                                                                          ))}
                                                                                                                                                                                                  </select>
                                                                                                                                                                                                        </Field>
                                                                                                                                                                                                              <Field label="Ring style">
                                                                                                                                                                                                                      <select style={inputStyle} value={style} onChange={(e) => setStyle(e.target.value)}>
                                                                                                                                                                                                                                <option value="phone">Phone ring</option>
                                                                                                                                                                                                                                          <option value="bell">Bell</option>
                                                                                                                                                                                                                                                    <option value="chime">Soft chime</option>
                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                  </Field>
                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                onClick={() => {
                                                                                                                                                                                                                                                                                          unlockAudio()
                                                                                                                                                                                                                                                                                                    ringOnce()
                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                    style={{ marginTop: 12, padding: '10px 16px', fontSize: 15, borderRadius: 10, border: '1.5px solid #d9d9d9', background: '#fff' }}
                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                  🔔 Test sound
                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                              <SaveBar onSave={() => save({ alert_repeat_seconds: repeat, alert_max_rings: maxRings, alert_style: style })} />
                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    export function ThemeSection({ row, save }: SectionProps) {
                                                                                                                                                                                                                                                                                                                                                      const [selected, setSelected] = useState<BackgroundKey>((row.dashboard_background ?? 'terracotta') as BackgroundKey)
                                                                                                                                                                                                                                                                                                                                                        const entries = Object.entries(BACKGROUND_PATTERNS) as [BackgroundKey, (typeof BACKGROUND_PATTERNS)[BackgroundKey]][]

                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                              <Card title="Dashboard theme" hint="Choose a colour theme for your dashboard sidebar.">
                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                            {entries.map(([key, pattern]) => (
                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                  key={key}
                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setSelected(key)}
                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 110,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    overflow: 'hidden',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: selected === key ? '3px solid #333' : '3px solid transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ height: 56, background: pattern.swatch }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ padding: '6px 4px', fontSize: 14 }}>{pattern.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <SaveBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onSave={async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const err = await save({ dashboard_background: selected })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!err) window.location.reload()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return err
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  