import { useState } from 'react'
import { COUNTRIES } from '../customer/checkoutHelpers'
import { Card, Field, Check, SaveBar, inputStyle, num } from './settingsKit'
import type { SectionProps } from './settingsKit'

export function DetailsSection({ row, save }: SectionProps) {
  const [name, setName] = useState(row.name ?? '')
    const [phone, setPhone] = useState(row.phone ?? '')
      const [whatsapp, setWhatsapp] = useState(row.whatsapp_number ?? '')
        const [city, setCity] = useState(row.city ?? '')
          const [slogan, setSlogan] = useState(row.slogan ?? '')
            const [footer, setFooter] = useState(row.receipt_footer ?? '')
              const [open, setOpen] = useState(row.status !== 'closed')

                return (
                    <Card title="Restaurant details">
                          <Field label="Restaurant name">
                                  <input style={inputStyle} value={name} onChange={(e) => setName(e.target.value)} />
                                        </Field>
                                              <Field label="Slogan">
                                                      <input style={inputStyle} value={slogan} onChange={(e) => setSlogan(e.target.value)} />
                                                            </Field>
                                                                  <Field label="City / area">
                                                                          <input style={inputStyle} value={city} onChange={(e) => setCity(e.target.value)} />
                                                                                </Field>
                                                                                      <Field label="Phone number">
                                                                                              <input style={inputStyle} value={phone} inputMode="tel" onChange={(e) => setPhone(e.target.value)} />
                                                                                                    </Field>
                                                                                                          <Field label="WhatsApp number">
                                                                                                                  <input style={inputStyle} value={whatsapp} inputMode="tel" onChange={(e) => setWhatsapp(e.target.value)} />
                                                                                                                        </Field>
                                                                                                                              <Field label="Receipt footer message">
                                                                                                                                      <input
                                                                                                                                                style={inputStyle}
                                                                                                                                                          value={footer}
                                                                                                                                                                    placeholder="Thank you for eating with us!"
                                                                                                                                                                              onChange={(e) => setFooter(e.target.value)}
                                                                                                                                                                                      />
                                                                                                                                                                                            </Field>
                                                                                                                                                                                                  <Check checked={open} onChange={setOpen} label="Accepting orders (untick to close)" />
                                                                                                                                                                                                        <SaveBar
                                                                                                                                                                                                                onSave={() =>
                                                                                                                                                                                                                          save({
                                                                                                                                                                                                                                      name: name.trim() || row.name,
                                                                                                                                                                                                                                                  slogan: slogan.trim() || null,
                                                                                                                                                                                                                                                              city: city.trim() || null,
                                                                                                                                                                                                                                                                          phone: phone.trim() || null,
                                                                                                                                                                                                                                                                                      whatsapp_number: whatsapp.trim() || null,
                                                                                                                                                                                                                                                                                                  receipt_footer: footer.trim() || null,
                                                                                                                                                                                                                                                                                                              status: open ? (row.status === 'closed' ? 'active' : row.status) : 'closed',
                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                            export function FeesSection({ row, save }: SectionProps) {
                                                                                                                                                                                                                                                                                                                                              const [cc, setCc] = useState(row.country_code ?? '+234')
                                                                                                                                                                                                                                                                                                                                                const [delivery, setDelivery] = useState(String(row.delivery_fee ?? 0))
                                                                                                                                                                                                                                                                                                                                                  const [takeaway, setTakeaway] = useState(String(row.takeaway_fee ?? 0))
                                                                                                                                                                                                                                                                                                                                                    const [minDelivery, setMinDelivery] = useState(String(row.min_delivery_order ?? 0))
                                                                                                                                                                                                                                                                                                                                                      const [prep, setPrep] = useState(String(row.prep_time_minutes ?? 25))

                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                            <Card title="Fees and ordering" hint="Amounts are in naira. Use 0 for no fee.">
                                                                                                                                                                                                                                                                                                                                                                  <Field label="Customer phone country code">
                                                                                                                                                                                                                                                                                                                                                                          <select style={inputStyle} value={cc} onChange={(e) => setCc(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                    {COUNTRIES.map((c) => (
                                                                                                                                                                                                                                                                                                                                                                                                <option key={c.code} value={c.code}>
                                                                                                                                                                                                                                                                                                                                                                                                              {c.label}
                                                                                                                                                                                                                                                                                                                                                                                                                          </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Field>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Field label="Delivery fee (₦)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input style={inputStyle} value={delivery} inputMode="decimal" onChange={(e) => setDelivery(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Field>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Field label="Takeaway pack fee (₦)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input style={inputStyle} value={takeaway} inputMode="decimal" onChange={(e) => setTakeaway(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Field>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Field label="Minimum order for delivery (₦)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input style={inputStyle} value={minDelivery} inputMode="decimal" onChange={(e) => setMinDelivery(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Field>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Field label="Estimated preparation time (minutes)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input style={inputStyle} value={prep} inputMode="numeric" onChange={(e) => setPrep(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Field>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <SaveBar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onSave={() =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          save({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      country_code: cc,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  delivery_fee: Math.max(0, num(delivery)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              takeaway_fee: Math.max(0, num(takeaway)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          min_delivery_order: Math.max(0, num(minDelivery)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prep_time_minutes: Math.max(1, Math.round(num(prep, 25))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    