import { useState } from 'react'
import { Card, Field, Check, SaveBar, inputStyle, num } from './settingsKit'
import type { SectionProps } from './settingsKit'

export function LoyaltySection({ row, save }: SectionProps) {
  const [on, setOn] = useState(!!row.loyalty_enabled)
    const [orders, setOrders] = useState(String(row.loyalty_min_orders ?? 15))
      const [days, setDays] = useState(String(row.loyalty_window_days ?? 60))
        const [type, setType] = useState(row.loyalty_reward_type ?? 'free_delivery')
          const [value, setValue] = useState(String(row.loyalty_reward_value ?? 0))

            return (
                <Card
                      title="Loyalty rewards"
                            hint="A customer who places enough paid orders within the time window gets a reward on their next order."
                                >
                                      <Check checked={on} onChange={setOn} label="Loyalty rewards on" />
                                            <Field label="Paid orders needed">
                                                    <input style={inputStyle} value={orders} inputMode="numeric" onChange={(e) => setOrders(e.target.value)} />
                                                          </Field>
                                                                <Field label="Within how many days">
                                                                        <input style={inputStyle} value={days} inputMode="numeric" onChange={(e) => setDays(e.target.value)} />
                                                                              </Field>
                                                                                    <Field label="Reward">
                                                                                            <select style={inputStyle} value={type} onChange={(e) => setType(e.target.value)}>
                                                                                                      <option value="free_delivery">Free delivery</option>
                                                                                                                <option value="free_food">Free food (up to an amount)</option>
                                                                                                                        </select>
                                                                                                                              </Field>
                                                                                                                                    {type === 'free_food' && (
                                                                                                                                            <Field label="Free food value (₦)">
                                                                                                                                                      <input style={inputStyle} value={value} inputMode="decimal" onChange={(e) => setValue(e.target.value)} />
                                                                                                                                                              </Field>
                                                                                                                                                                    )}
                                                                                                                                                                          <SaveBar
                                                                                                                                                                                  onSave={() =>
                                                                                                                                                                                            save({
                                                                                                                                                                                                        loyalty_enabled: on,
                                                                                                                                                                                                                    loyalty_min_orders: Math.max(1, Math.round(num(orders, 15))),
                                                                                                                                                                                                                                loyalty_window_days: Math.max(1, Math.round(num(days, 60))),
                                                                                                                                                                                                                                            loyalty_reward_type: type,
                                                                                                                                                                                                                                                        loyalty_reward_value: type === 'free_food' ? Math.max(0, num(value)) : 0,
                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                      export function TaxSection({ row, save }: SectionProps) {
                                                                                                                                                                                                                                                                                        const [vat, setVat] = useState(String(row.vat_percent ?? 0))
                                                                                                                                                                                                                                                                                          const [service, setService] = useState(String(row.service_charge_percent ?? 0))

                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <Card
                                                                                                                                                                                                                                                                                                      title="VAT and service charge"
                                                                                                                                                                                                                                                                                                            hint="Service charge is a percentage of the food total. VAT is applied to food plus service charge. Delivery and takeaway fees are not taxed. Ask your accountant which rates apply to you."
                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                      <Field label="Service charge (%)">
                                                                                                                                                                                                                                                                                                                              <input style={inputStyle} value={service} inputMode="decimal" onChange={(e) => setService(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                    </Field>
                                                                                                                                                                                                                                                                                                                                          <Field label="VAT (%)">
                                                                                                                                                                                                                                                                                                                                                  <input style={inputStyle} value={vat} inputMode="decimal" onChange={(e) => setVat(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                        </Field>
                                                                                                                                                                                                                                                                                                                                                              <SaveBar
                                                                                                                                                                                                                                                                                                                                                                      onSave={() =>
                                                                                                                                                                                                                                                                                                                                                                                save({
                                                                                                                                                                                                                                                                                                                                                                                            vat_percent: Math.min(100, Math.max(0, num(vat))),
                                                                                                                                                                                                                                                                                                                                                                                                        service_charge_percent: Math.min(100, Math.max(0, num(service))),
                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      