import { useCallback, useEffect, useState } from 'react'
import type { CSSProperties, ReactNode } from 'react'
import { supabase } from '../../lib/supabaseClient'

export type DayHours = { closed: boolean; open: string; close: string }

export type RestaurantRow = {
  id: string
    name: string | null
      phone: string | null
        city: string | null
          slogan: string | null
            status: string | null
              whatsapp_number: string | null
                receipt_footer: string | null
                  country_code: string | null
                    delivery_fee: number | null
                      takeaway_fee: number | null
                        min_delivery_order: number | null
                          prep_time_minutes: number | null
                            alert_repeat_seconds: number | null
                              alert_max_rings: number | null
                                alert_style: string | null
                                  loyalty_enabled: boolean | null
                                    loyalty_min_orders: number | null
                                      loyalty_window_days: number | null
                                        loyalty_reward_type: string | null
                                          loyalty_reward_value: number | null
                                            vat_percent: number | null
                                              service_charge_percent: number | null
                                                use_opening_hours: boolean | null
                                                  opening_hours: Record<string, DayHours> | null
                                                    dashboard_background: string | null
                                                    }

                                                    const COLUMNS = [
                                                      'id', 'name', 'phone', 'city', 'slogan', 'status', 'whatsapp_number', 'receipt_footer',
                                                        'country_code', 'delivery_fee', 'takeaway_fee', 'min_delivery_order', 'prep_time_minutes',
                                                          'alert_repeat_seconds', 'alert_max_rings', 'alert_style', 'loyalty_enabled',
                                                            'loyalty_min_orders', 'loyalty_window_days', 'loyalty_reward_type', 'loyalty_reward_value',
                                                              'vat_percent', 'service_charge_percent', 'use_opening_hours', 'opening_hours',
                                                                'dashboard_background',
                                                                ].join(',')

                                                                export type SaveFn = (patch: Partial<RestaurantRow>) => Promise<string>
                                                                export type SectionProps = { row: RestaurantRow; save: SaveFn }

                                                                export function useRestaurant(restaurantId?: string | null) {
                                                                  const [row, setRow] = useState<RestaurantRow | null>(null)
                                                                    const [error, setError] = useState('')

                                                                      useEffect(() => {
                                                                          if (!restaurantId) return
                                                                              supabase
                                                                                    .from('restaurants')
                                                                                          .select(COLUMNS)
                                                                                                .eq('id', restaurantId)
                                                                                                      .single()
                                                                                                            .then(({ data, error: err }) => {
                                                                                                                    if (err) setError(err.message)
                                                                                                                            else setRow(data as unknown as RestaurantRow)
                                                                                                                                  })
                                                                                                                                    }, [restaurantId])

                                                                                                                                      const save: SaveFn = useCallback(
                                                                                                                                          async (patch) => {
                                                                                                                                                if (!restaurantId) return 'Not signed in'
                                                                                                                                                      const { error: err } = await supabase.from('restaurants').update(patch).eq('id', restaurantId)
                                                                                                                                                            if (err) return err.message
                                                                                                                                                                  setRow((r) => (r ? { ...r, ...patch } : r))
                                                                                                                                                                        return ''
                                                                                                                                                                            },
                                                                                                                                                                                [restaurantId]
                                                                                                                                                                                  )

                                                                                                                                                                                    return { row, error, save }
                                                                                                                                                                                    }

                                                                                                                                                                                    export const num = (v: string, fallback = 0) => {
                                                                                                                                                                                      const n = parseFloat(v)
                                                                                                                                                                                        return Number.isFinite(n) ? n : fallback
                                                                                                                                                                                        }

                                                                                                                                                                                        export const inputStyle: CSSProperties = {
                                                                                                                                                                                          width: '100%',
                                                                                                                                                                                            padding: '12px 14px',
                                                                                                                                                                                              fontSize: 16,
                                                                                                                                                                                                border: '1.5px solid #d9d9d9',
                                                                                                                                                                                                  borderRadius: 10,
                                                                                                                                                                                                    background: '#fff',
                                                                                                                                                                                                    }

                                                                                                                                                                                                    export function Card(p: { title: string; hint?: string; children: ReactNode }) {
                                                                                                                                                                                                      return (
                                                                                                                                                                                                          <div
                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                        background: '#fff',
                                                                                                                                                                                                                                borderRadius: 16,
                                                                                                                                                                                                                                        padding: 16,
                                                                                                                                                                                                                                                marginBottom: 14,
                                                                                                                                                                                                                                                        boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                        <h3 style={{ margin: 0, fontSize: 19 }}>{p.title}</h3>
                                                                                                                                                                                                                                                                              {p.hint && <p style={{ margin: '4px 0 6px', color: '#6b6b6b', fontSize: 14 }}>{p.hint}</p>}
                                                                                                                                                                                                                                                                                    {p.children}
                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                          export function Field(p: { label: string; children: ReactNode }) {
                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <label style={{ display: 'block', marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                      <span style={{ display: 'block', fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{p.label}</span>
                                                                                                                                                                                                                                                                                                            {p.children}
                                                                                                                                                                                                                                                                                                                </label>
                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                  export function Check(p: { checked: boolean; onChange: (v: boolean) => void; label: string }) {
                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                        <label style={{ display: 'flex', alignItems: 'center', gap: 10, marginTop: 12, fontSize: 16, fontWeight: 600 }}>
                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                      type="checkbox"
                                                                                                                                                                                                                                                                                                                                              checked={p.checked}
                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => p.onChange(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                              style={{ width: 22, height: 22 }}
                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                          {p.label}
                                                                                                                                                                                                                                                                                                                                                                              </label>
                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                export function SaveBar(p: { onSave: () => Promise<string> }) {
                                                                                                                                                                                                                                                                                                                                                                                  const [busy, setBusy] = useState(false)
                                                                                                                                                                                                                                                                                                                                                                                    const [msg, setMsg] = useState('')
                                                                                                                                                                                                                                                                                                                                                                                      const [ok, setOk] = useState(false)

                                                                                                                                                                                                                                                                                                                                                                                        async function go() {
                                                                                                                                                                                                                                                                                                                                                                                            setBusy(true)
                                                                                                                                                                                                                                                                                                                                                                                                setMsg('')
                                                                                                                                                                                                                                                                                                                                                                                                    const err = await p.onSave()
                                                                                                                                                                                                                                                                                                                                                                                                        setBusy(false)
                                                                                                                                                                                                                                                                                                                                                                                                            setOk(!err)
                                                                                                                                                                                                                                                                                                                                                                                                                setMsg(err || 'Saved ✓')
                                                                                                                                                                                                                                                                                                                                                                                                                    if (!err) setTimeout(() => setMsg(''), 2500)
                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginTop: 14 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={go}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={busy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '11px 20px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: busy ? '#c9c3bd' : '#2b1b12',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {busy ? 'Saving...' : 'Save'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {msg && <span style={{ fontSize: 15, color: ok ? '#15803d' : '#b91c1c' }}>{msg}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        