import { useEffect, useState } from 'react'
import { useAuth } from '../../hooks/useAuth'
import { supabase } from '../../lib/supabaseClient'
import { BACKGROUND_PATTERNS, type BackgroundKey } from '../../lib/backgroundPatterns'

export default function Settings() {
  const { profile } = useAuth()
    const restaurantId = profile?.restaurant_id

      const [current, setCurrent] = useState<BackgroundKey>('terracotta')
        const [selected, setSelected] = useState<BackgroundKey>('terracotta')
          const [loading, setLoading] = useState(true)
            const [saving, setSaving] = useState(false)
              const [error, setError] = useState('')
                const [saved, setSaved] = useState(false)

                  useEffect(() => {
                      async function load() {
                            if (!restaurantId) return
                                  const { data, error: err } = await supabase
                                          .from('restaurants')
                                                  .select('dashboard_background')
                                                          .eq('id', restaurantId)
                                                                  .single()

                                                                        if (err) {
                                                                                setError(err.message)
                                                                                      } else if (data?.dashboard_background) {
                                                                                              const bg = data.dashboard_background as BackgroundKey
                                                                                                      setCurrent(bg)
                                                                                                              setSelected(bg)
                                                                                                                    }
                                                                                                                          setLoading(false)
                                                                                                                              }
                                                                                                                                  load()
                                                                                                                                    }, [restaurantId])

                                                                                                                                      async function handleSave() {
                                                                                                                                          if (!restaurantId) return
                                                                                                                                              setSaving(true)
                                                                                                                                                  setError('')
                                                                                                                                                      setSaved(false)

                                                                                                                                                          const { error: err } = await supabase
                                                                                                                                                                .from('restaurants')
                                                                                                                                                                      .update({ dashboard_background: selected })
                                                                                                                                                                            .eq('id', restaurantId)

                                                                                                                                                                                setSaving(false)

                                                                                                                                                                                    if (err) {
                                                                                                                                                                                          setError(err.message)
                                                                                                                                                                                                return
                                                                                                                                                                                                    }

                                                                                                                                                                                                        setCurrent(selected)
                                                                                                                                                                                                            setSaved(true)
                                                                                                                                                                                                                window.location.reload()
                                                                                                                                                                                                                  }

                                                                                                                                                                                                                    if (!restaurantId || loading) {
                                                                                                                                                                                                                        return <div style={{ padding: 24 }}>Loading...</div>
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                <div style={{ padding: 16, maxWidth: 640 }}>
                                                                                                                                                                                                                                      <h2>Settings</h2>

                                                                                                                                                                                                                                            <h3 style={{ marginTop: 24 }}>Dashboard theme</h3>
                                                                                                                                                                                                                                                  <p style={{ color: '#666', fontSize: 14 }}>
                                                                                                                                                                                                                                                          Choose a color theme for your dashboard sidebar.
                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: 12, marginTop: 12, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                              {(Object.entries(BACKGROUND_PATTERNS) as [BackgroundKey, typeof BACKGROUND_PATTERNS[BackgroundKey]][]).map(
                                                                                                                                                                                                                                                                                        ([key, pattern]) => (
                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                  key={key}
                                                                                                                                                                                                                                                                                                                                onClick={() => setSelected(key)}
                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                              cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                              border: selected === key ? '3px solid #333' : '3px solid transparent',
                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                              padding: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                              overflow: 'hidden',
                                                                                                                                                                                                                                                                                                                                                                                                                                              width: 140,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ background: pattern.swatch, height: 70 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ padding: '8px 10px', fontSize: 13, textAlign: 'left', background: '#fff' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {pattern.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {current === key && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 11, color: '#2f855a', marginTop: 2 }}>Current</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {error && <p style={{ color: 'red', marginTop: 12 }}>{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {saved && <p style={{ color: '#2f855a', marginTop: 12 }}>Saved. Reloading...</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handleSave}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={saving || selected === current}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: '10px 24px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: selected === current ? '#ccc' : '#333',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: selected === current ? 'default' : 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {saving ? 'Saving...' : 'Save theme'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          