import { useCallback, useEffect, useRef, useState } from 'react'
import { useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabaseClient'
import { ringOnce, unlockAudio } from './orderRing'

export type OrderAlert = {
  id: string
    orderNumber: string
      total: number
        orderType: string
        }

        const RING_EVERY_MS = 4000 // use 10000 for a calmer 10-second reminder
        const PENDING_WINDOW_HOURS = 12

        const isLivePath = (p: string) =>
          /^\/dashboard(\/(orders|kitchen|payments|reports))?\/?$/.test(p)

          const isPending = (r: Record<string, unknown>) =>
            r.payment_status === 'success' && r.status === 'confirmed'

            const toAlert = (r: Record<string, unknown>): OrderAlert => ({
              id: String(r.id),
                orderNumber: String(r.order_number ?? ''),
                  total: Number(r.total ?? 0),
                    orderType: String(r.order_type ?? ''),
                    })

                    export function useOrderAlerts(restaurantId?: string | null) {
                      const { pathname } = useLocation()
                        const [pending, setPending] = useState<OrderAlert[]>([])
                          const [version, setVersion] = useState(0)
                            const [soundOn, setSoundOn] = useState(() => localStorage.getItem('order_sound') === '1')
                              const known = useRef(new Set<string>())
                                const baseTitle = useRef(document.title)

                                  const enableSound = useCallback(() => {
                                      unlockAudio()
                                          localStorage.setItem('order_sound', '1')
                                              setSoundOn(true)
                                                  ringOnce()
                                                    }, [])

                                                      // Browsers only allow audio after a tap, so wake it on any tap
                                                        useEffect(() => {
                                                            if (!soundOn) return
                                                                const wake = () => unlockAudio()
                                                                    window.addEventListener('pointerdown', wake)
                                                                        return () => window.removeEventListener('pointerdown', wake)
                                                                          }, [soundOn])

                                                                            useEffect(() => {
                                                                                if (!restaurantId) return
                                                                                    const rid = restaurantId
                                                                                        let active = true

                                                                                            async function loadPending() {
                                                                                                  const since = new Date(Date.now() - PENDING_WINDOW_HOURS * 3600 * 1000).toISOString()
                                                                                                        const { data } = await supabase
                                                                                                                .from('orders')
                                                                                                                        .select('id,order_number,total,order_type,status,payment_status')
                                                                                                                                .eq('restaurant_id', rid)
                                                                                                                                        .eq('payment_status', 'success')
                                                                                                                                                .eq('status', 'confirmed')
                                                                                                                                                        .gte('created_at', since)
                                                                                                                                                                .order('created_at', { ascending: false })
                                                                                                                                                                        .limit(50)
                                                                                                                                                                              if (!active || !data) return
                                                                                                                                                                                    known.current = new Set(data.map((r) => String(r.id)))
                                                                                                                                                                                          setPending(data.map((r) => toAlert(r)))
                                                                                                                                                                                              }
                                                                                                                                                                                                  loadPending()

                                                                                                                                                                                                      const channel = supabase
                                                                                                                                                                                                            .channel(`orders-${rid}`)
                                                                                                                                                                                                                  .on(
                                                                                                                                                                                                                          'postgres_changes',
                                                                                                                                                                                                                                  { event: '*', schema: 'public', table: 'orders', filter: `restaurant_id=eq.${rid}` },
                                                                                                                                                                                                                                          (payload) => {
                                                                                                                                                                                                                                                    const row = payload.new as Record<string, unknown> | undefined
                                                                                                                                                                                                                                                              if (!row || !('id' in row)) return
                                                                                                                                                                                                                                                                        const id = String(row.id)
                                                                                                                                                                                                                                                                                  if (isPending(row)) {
                                                                                                                                                                                                                                                                                              if (known.current.has(id)) return
                                                                                                                                                                                                                                                                                                          const created = new Date(String(row.created_at)).getTime()
                                                                                                                                                                                                                                                                                                                      if (Date.now() - created > PENDING_WINDOW_HOURS * 3600 * 1000) return
                                                                                                                                                                                                                                                                                                                                  known.current.add(id)
                                                                                                                                                                                                                                                                                                                                              setPending((p) => [toAlert(row), ...p])
                                                                                                                                                                                                                                                                                                                                                          setVersion((v) => v + 1)
                                                                                                                                                                                                                                                                                                                                                                    } else if (known.current.has(id)) {
                                                                                                                                                                                                                                                                                                                                                                                known.current.delete(id)
                                                                                                                                                                                                                                                                                                                                                                                            setPending((p) => p.filter((x) => x.id !== id))
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                          .subscribe()

                                                                                                                                                                                                                                                                                                                                                                                                                              // Catch anything missed while the phone was asleep
                                                                                                                                                                                                                                                                                                                                                                                                                                  const onVisible = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (document.visibilityState === 'visible') loadPending()
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                document.addEventListener('visibilitychange', onVisible)

                                                                                                                                                                                                                                                                                                                                                                                                                                                    return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          active = false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.removeEventListener('visibilitychange', onVisible)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      supabase.removeChannel(channel)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [restaurantId])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Ring again and again until nothing is waiting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const hasPending = pending.length > 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!soundOn || !hasPending) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ringOnce()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const t = setInterval(ringOnce, RING_EVERY_MS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => clearInterval(t)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, [soundOn, hasPending])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.title = pending.length > 0 ? `(${pending.length}) NEW ORDER!` : baseTitle.current
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, [pending.length])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Keep the screen awake so a tablet doesn't lock and go silent
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!soundOn || !('wakeLock' in navigator)) return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let lock: WakeLockSentinel | null = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const request = async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lock = await navigator.wakeLock.request('screen')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /* not available */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      request()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const onVisible = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (document.visibilityState === 'visible') request()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.addEventListener('visibilitychange', onVisible)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  document.removeEventListener('visibilitychange', onVisible)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        lock?.release().catch(() => {})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [soundOn])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // "dismiss" here means ACCEPT: the order moves to Preparing and the ringing stops
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const accept = useCallback(async (id: string) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const { error } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .from('orders')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .update({ status: 'preparing', preparing_at: new Date().toISOString() })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .eq('id', id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  known.current.delete(id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setPending((p) => p.filter((x) => x.id !== id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alerts: pending,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        unseen: pending.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            soundOn,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                enableSound,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dismiss: accept,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        refreshKey: isLivePath(pathname) ? version : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          