import { supabase } from '../../../lib/supabaseClient'

export type RangeKey = 'today' | '7d' | '30d' | '90d'

export const RANGES: { key: RangeKey; label: string; days: number }[] = [
  { key: 'today', label: 'Today', days: 1 },
    { key: '7d', label: '7 days', days: 7 },
      { key: '30d', label: '30 days', days: 30 },
        { key: '90d', label: '90 days', days: 90 },
        ]

        type OrderRow = {
          id: string
            customer_id: string | null
              order_type: string
                status: string
                  payment_status: string
                    total: number
                      discount: number | null
                        loyalty_reward_applied: boolean | null
                          created_at: string
                          }

                          type ItemRow = { order_id: string; item_name: string; item_price: number; quantity: number }
                          type Point = { label: string; revenue: number; orders: number }

                          export type Report = {
                            revenue: number
                              orders: number
                                aov: number
                                  customers: number
                                    repeat: number
                                      dRevenue: number | null
                                        dOrders: number | null
                                          dAov: number | null
                                            trend: Point[]
                                              hours: { label: string; orders: number }[]
                                                types: { name: string; value: number; revenue: number }[]
                                                  top: { name: string; qty: number; revenue: number }[]
                                                    statuses: { name: string; value: number }[]
                                                      conversion: number
                                                        rewards: number
                                                          discounts: number
                                                            peakHour: string
                                                              bestDay: string
                                                              }

                                                              const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
                                                              const TYPE_NAMES: Record<string, string> = { dine_in: 'Dine-in', takeaway: 'Takeaway', delivery: 'Delivery' }

                                                              const isPaid = (o: OrderRow) => ['success', 'paid'].includes((o.payment_status || '').toLowerCase())
                                                              const startOfDay = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate())
                                                              const dayKey = (d: Date) => `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`
                                                              const pct = (cur: number, prev: number) =>
                                                                prev === 0 ? (cur === 0 ? 0 : null) : ((cur - prev) / prev) * 100
                                                                const hourLabel = (h: number) =>
                                                                  h === 0 ? '12am' : h < 12 ? `${h}am` : h === 12 ? '12pm' : `${h - 12}pm`
                                                                  const sum = (rows: OrderRow[]) => rows.reduce((s, o) => s + Number(o.total || 0), 0)

                                                                  export async function loadReport(restaurantId: string, rangeKey: RangeKey): Promise<Report> {
                                                                    const days = RANGES.find((r) => r.key === rangeKey)?.days ?? 7
                                                                      const start = startOfDay(new Date())
                                                                        start.setDate(start.getDate() - (days - 1))
                                                                          const prevStart = new Date(start)
                                                                            prevStart.setDate(prevStart.getDate() - days)

                                                                              const { data, error } = await supabase
                                                                                  .from('orders')
                                                                                      .select('id,customer_id,order_type,status,payment_status,total,discount,loyalty_reward_applied,created_at')
                                                                                          .eq('restaurant_id', restaurantId)
                                                                                              .gte('created_at', prevStart.toISOString())
                                                                                                  .order('created_at', { ascending: false })
                                                                                                      .limit(1000)
                                                                                                        if (error) throw new Error(error.message)

                                                                                                          const all = (data ?? []) as OrderRow[]
                                                                                                            const cur = all.filter((o) => new Date(o.created_at) >= start)
                                                                                                              const curPaid = cur.filter(isPaid)
                                                                                                                const prevPaid = all.filter((o) => new Date(o.created_at) < start).filter(isPaid)

                                                                                                                  // Dishes sold
                                                                                                                    const ids = curPaid.map((o) => o.id)
                                                                                                                      const chunks: string[][] = []
                                                                                                                        for (let i = 0; i < ids.length; i += 100) chunks.push(ids.slice(i, i + 100))
                                                                                                                          const results = await Promise.all(
                                                                                                                              chunks.map((c) =>
                                                                                                                                    supabase.from('order_items').select('order_id,item_name,item_price,quantity').in('order_id', c)
                                                                                                                                        )
                                                                                                                                          )
                                                                                                                                            const items = results.flatMap((r) => (r.data ?? []) as ItemRow[])
                                                                                                                                              const dishes = new Map<string, { qty: number; revenue: number }>()
                                                                                                                                                for (const it of items) {
                                                                                                                                                    const d = dishes.get(it.item_name) ?? { qty: 0, revenue: 0 }
                                                                                                                                                        d.qty += Number(it.quantity)
                                                                                                                                                            d.revenue += Number(it.item_price) * Number(it.quantity)
                                                                                                                                                                dishes.set(it.item_name, d)
                                                                                                                                                                  }
                                                                                                                                                                    const top = [...dishes.entries()]
                                                                                                                                                                        .map(([name, v]) => ({ name, ...v }))
                                                                                                                                                                            .sort((a, b) => b.revenue - a.revenue)
                                                                                                                                                                                .slice(0, 6)

                                                                                                                                                                                  // Headline numbers
                                                                                                                                                                                    const revenue = sum(curPaid)
                                                                                                                                                                                      const orders = curPaid.length
                                                                                                                                                                                        const aov = orders ? revenue / orders : 0
                                                                                                                                                                                          const prevAov = prevPaid.length ? sum(prevPaid) / prevPaid.length : 0

                                                                                                                                                                                            const perCustomer = new Map<string, number>()
                                                                                                                                                                                              for (const o of curPaid) {
                                                                                                                                                                                                  if (o.customer_id) perCustomer.set(o.customer_id, (perCustomer.get(o.customer_id) ?? 0) + 1)
                                                                                                                                                                                                    }
                                                                                                                                                                                                      const repeat = [...perCustomer.values()].filter((n) => n > 1).length

                                                                                                                                                                                                        // Revenue over time
                                                                                                                                                                                                          let trend: Point[]
                                                                                                                                                                                                            if (days === 1) {
                                                                                                                                                                                                                trend = Array.from({ length: 24 }, (_, h) => ({ label: hourLabel(h), revenue: 0, orders: 0 }))
                                                                                                                                                                                                                    for (const o of curPaid) {
                                                                                                                                                                                                                          const p = trend[new Date(o.created_at).getHours()]
                                                                                                                                                                                                                                p.revenue += Number(o.total)
                                                                                                                                                                                                                                      p.orders += 1
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                const byDay = new Map<string, Point>()
                                                                                                                                                                                                                                                    trend = []
                                                                                                                                                                                                                                                        for (let i = 0; i < days; i++) {
                                                                                                                                                                                                                                                              const d = new Date(start)
                                                                                                                                                                                                                                                                    d.setDate(start.getDate() + i)
                                                                                                                                                                                                                                                                          const p: Point = {
                                                                                                                                                                                                                                                                                  label: d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }),
                                                                                                                                                                                                                                                                                          revenue: 0,
                                                                                                                                                                                                                                                                                                  orders: 0,
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                              byDay.set(dayKey(d), p)
                                                                                                                                                                                                                                                                                                                    trend.push(p)
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                            for (const o of curPaid) {
                                                                                                                                                                                                                                                                                                                                  const p = byDay.get(dayKey(new Date(o.created_at)))
                                                                                                                                                                                                                                                                                                                                        if (p) {
                                                                                                                                                                                                                                                                                                                                                p.revenue += Number(o.total)
                                                                                                                                                                                                                                                                                                                                                        p.orders += 1
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                      // Busiest hours and best weekday
                                                                                                                                                                                                                                                                                                                                                                        const hours = Array.from({ length: 24 }, (_, h) => ({ label: hourLabel(h), orders: 0 }))
                                                                                                                                                                                                                                                                                                                                                                          const weekday = new Array<number>(7).fill(0)
                                                                                                                                                                                                                                                                                                                                                                            for (const o of curPaid) {
                                                                                                                                                                                                                                                                                                                                                                                const d = new Date(o.created_at)
                                                                                                                                                                                                                                                                                                                                                                                    hours[d.getHours()].orders += 1
                                                                                                                                                                                                                                                                                                                                                                                        weekday[d.getDay()] += Number(o.total)
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                            const peak = hours.reduce((a, b) => (b.orders > a.orders ? b : a), hours[0])
                                                                                                                                                                                                                                                                                                                                                                                              const bestIdx = weekday.indexOf(Math.max(...weekday))

                                                                                                                                                                                                                                                                                                                                                                                                // Order types and progress
                                                                                                                                                                                                                                                                                                                                                                                                  const types = ['dine_in', 'takeaway', 'delivery'].map((t) => {
                                                                                                                                                                                                                                                                                                                                                                                                      const rows = curPaid.filter((o) => o.order_type === t)
                                                                                                                                                                                                                                                                                                                                                                                                          return { name: TYPE_NAMES[t], value: rows.length, revenue: sum(rows) }
                                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                              const count = (s: string) => curPaid.filter((o) => o.status === s).length
                                                                                                                                                                                                                                                                                                                                                                                                                const statuses = [
                                                                                                                                                                                                                                                                                                                                                                                                                    { name: 'Waiting to be accepted', value: count('confirmed') },
                                                                                                                                                                                                                                                                                                                                                                                                                        { name: 'Preparing', value: count('preparing') },
                                                                                                                                                                                                                                                                                                                                                                                                                            { name: 'Ready', value: count('ready') },
                                                                                                                                                                                                                                                                                                                                                                                                                                { name: 'Completed', value: count('completed') },
                                                                                                                                                                                                                                                                                                                                                                                                                                    { name: 'Payment not completed', value: cur.length - curPaid.length },
                                                                                                                                                                                                                                                                                                                                                                                                                                      ]

                                                                                                                                                                                                                                                                                                                                                                                                                                        const rewarded = curPaid.filter((o) => o.loyalty_reward_applied)

                                                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                                              revenue,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  orders,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      aov,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          customers: perCustomer.size,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              repeat,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dRevenue: pct(revenue, sum(prevPaid)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      dOrders: pct(orders, prevPaid.length),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          dAov: pct(aov, prevAov),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              trend,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hours,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      types,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          top,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              statuses,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  conversion: cur.length ? (curPaid.length / cur.length) * 100 : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rewards: rewarded.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          discounts: rewarded.reduce((s, o) => s + Number(o.discount || 0), 0),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              peakHour: orders ? peak.label : '—',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bestDay: orders ? WEEKDAYS[bestIdx] : '—',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    