import type { OrderAlert } from '../hooks/useOrderAlerts'

interface Props {
  alerts: OrderAlert[]
    soundOn: boolean
      enableSound: () => void
        dismiss: (id: string) => void
          onOpen: () => void
          }

          const label = (t: string) =>
            t === 'dine_in' ? 'Dine-in' : t === 'takeaway' ? 'Takeaway' : t === 'delivery' ? 'Delivery' : t

            export function OrderAlerts(p: Props) {
              const shown = p.alerts.slice(0, 3)
                const more = p.alerts.length - shown.length

                  return (
                      <>
                            <style>{`@keyframes orderPulse{0%,100%{box-shadow:0 0 0 0 rgba(220,38,38,.75)}50%{box-shadow:0 0 0 14px rgba(220,38,38,0)}}`}</style>

                                  <div
                                          style={{
                                                    position: 'fixed',
                                                              top: 'calc(8px + env(safe-area-inset-top, 0px))',
                                                                        left: 8,
                                                                                  right: 8,
                                                                                            zIndex: 2000,
                                                                                                      display: 'flex',
                                                                                                                flexDirection: 'column',
                                                                                                                          alignItems: 'center',
                                                                                                                                    gap: 8,
                                                                                                                                              pointerEvents: 'none',
                                                                                                                                                      }}
                                                                                                                                                            >
                                                                                                                                                                    {shown.map((a) => (
                                                                                                                                                                              <div
                                                                                                                                                                                          key={a.id}
                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                    pointerEvents: 'auto',
                                                                                                                                                                                                                                  width: '100%',
                                                                                                                                                                                                                                                maxWidth: 480,
                                                                                                                                                                                                                                                              display: 'flex',
                                                                                                                                                                                                                                                                            alignItems: 'center',
                                                                                                                                                                                                                                                                                          gap: 12,
                                                                                                                                                                                                                                                                                                        background: '#dc2626',
                                                                                                                                                                                                                                                                                                                      color: '#fff',
                                                                                                                                                                                                                                                                                                                                    borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                  padding: '12px 14px',
                                                                                                                                                                                                                                                                                                                                                                animation: 'orderPulse 1.2s infinite',
                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                  <div onClick={p.onOpen} style={{ flex: 1, cursor: 'pointer' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontSize: 19, fontWeight: 800 }}>🚨 NEW ORDER {a.orderNumber}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ fontSize: 15 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              ₦{a.total.toLocaleString()} · {label(a.orderType)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => p.dismiss(a.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#b91c1c',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: '12px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 800,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ✔ Accept
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {more > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ pointerEvents: 'auto', background: '#7f1d1d', color: '#fff', borderRadius: 20, padding: '6px 14px', fontSize: 14, fontWeight: 700 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    +{more} more waiting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {!p.soundOn && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={p.enableSound}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          position: 'fixed',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      right: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bottom: 'calc(12px + env(safe-area-inset-bottom, 0px))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              zIndex: 2000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '12px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: '#2b1b12',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: 700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              boxShadow: '0 4px 14px rgba(0,0,0,0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          🔔 Turn on order sound
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              