import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../../lib/supabaseClient'

const inputStyle = { display: 'block', width: '100%', marginBottom: 10, padding: 10 }
const btnStyle = { padding: '10px 20px', marginTop: 12 }

export default function OnboardingWizard() {
  const navigate = useNavigate()
    const [step, setStep] = useState(1)
      const [error, setError] = useState('')
        const [loading, setLoading] = useState(false)

          // Step 1: Restaurant info
            const [restaurantName, setRestaurantName] = useState('')
              const [description, setDescription] = useState('')
                const [phone, setPhone] = useState('')
                  const [email, setEmail] = useState('')
                    const [address, setAddress] = useState('')
                      const [city, setCity] = useState('')
                        const [state, setState] = useState('')

                          // Step 2: Owner account
                            const [ownerName, setOwnerName] = useState('')
                              const [ownerEmail, setOwnerEmail] = useState('')
                                const [ownerPhone, setOwnerPhone] = useState('')
                                  const [password, setPassword] = useState('')

                                    // Step 3: Branding
                                      const [primaryColor, setPrimaryColor] = useState('#1a1a1a')
                                        const [secondaryColor, setSecondaryColor] = useState('#ffffff')
                                          const [currency, setCurrency] = useState('NGN')
                                            const [slogan, setSlogan] = useState('')

                                              function nextStep() {
                                                  setError('')
                                                      if (step === 1 && !restaurantName.trim()) {
                                                            setError('Restaurant name is required')
                                                                  return
                                                                      }
                                                                          if (step === 2 && (!ownerName.trim() || !ownerEmail.trim() || !password.trim())) {
                                                                                setError('Owner name, email and password are required')
                                                                                      return
                                                                                          }
                                                                                              setStep((s) => s + 1)
                                                                                                }

                                                                                                  function prevStep() {
                                                                                                      setError('')
                                                                                                          setStep((s) => s - 1)
                                                                                                            }

                                                                                                              async function handleFinish() {
                                                                                                                  setLoading(true)
                                                                                                                      setError('')

                                                                                                                          const { data: authData, error: authError } = await supabase.auth.signUp({
                                                                                                                                email: ownerEmail,
                                                                                                                                      password,
                                                                                                                                          })

                                                                                                                                              if (authError || !authData.user) {
                                                                                                                                                    setError(authError?.message || 'Signup failed')
                                                                                                                                                          setLoading(false)
                                                                                                                                                                return
                                                                                                                                                                    }

                                                                                                                                                                        const slug = restaurantName.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-')

                                                                                                                                                                            const { data: restaurant, error: restError } = await supabase
                                                                                                                                                                                  .from('restaurants')
                                                                                                                                                                                        .insert({
                                                                                                                                                                                                name: restaurantName,
                                                                                                                                                                                                        slug,
                                                                                                                                                                                                                description,
                                                                                                                                                                                                                        phone,
                                                                                                                                                                                                                                email,
                                                                                                                                                                                                                                        address,
                                                                                                                                                                                                                                                city,
                                                                                                                                                                                                                                                        state,
                                                                                                                                                                                                                                                                primary_color: primaryColor,
                                                                                                                                                                                                                                                                        secondary_color: secondaryColor,
                                                                                                                                                                                                                                                                                currency,
                                                                                                                                                                                                                                                                                        slogan,
                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                    .select()
                                                                                                                                                                                                                                                                                                          .single()

                                                                                                                                                                                                                                                                                                              if (restError || !restaurant) {
                                                                                                                                                                                                                                                                                                                    setError(restError?.message || 'Could not create restaurant')
                                                                                                                                                                                                                                                                                                                          setLoading(false)
                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        const { error: profileError } = await supabase.from('profiles').insert({
                                                                                                                                                                                                                                                                                                                                              id: authData.user.id,
                                                                                                                                                                                                                                                                                                                                                    restaurant_id: restaurant.id,
                                                                                                                                                                                                                                                                                                                                                          role: 'restaurant_owner',
                                                                                                                                                                                                                                                                                                                                                                full_name: ownerName,
                                                                                                                                                                                                                                                                                                                                                                      phone: ownerPhone,
                                                                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                                                              if (profileError) {
                                                                                                                                                                                                                                                                                                                                                                                    setError(profileError.message)
                                                                                                                                                                                                                                                                                                                                                                                          setLoading(false)
                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                        setLoading(false)
                                                                                                                                                                                                                                                                                                                                                                                                            alert(`${restaurantName} created! You can now log in.`)
                                                                                                                                                                                                                                                                                                                                                                                                                navigate('/login')
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ padding: 24, maxWidth: 420, margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <h1>Create Your Restaurant</h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Step {step} of 3</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                          {step === 1 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Restaurant Information</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input style={inputStyle} placeholder="Restaurant name" value={restaurantName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setRestaurantName(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input style={inputStyle} placeholder="Business description" value={description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setDescription(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input style={inputStyle} placeholder="Phone" value={phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPhone(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input style={inputStyle} placeholder="Business email" value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input style={inputStyle} placeholder="Address" value={address}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setAddress(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input style={inputStyle} placeholder="City" value={city}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setCity(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input style={inputStyle} placeholder="State" value={state}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setState(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {step === 2 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Owner Account</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input style={inputStyle} placeholder="Full name" value={ownerName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setOwnerName(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input style={inputStyle} placeholder="Email" type="email" value={ownerEmail}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setOwnerEmail(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input style={inputStyle} placeholder="Phone" value={ownerPhone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setOwnerPhone(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input style={inputStyle} placeholder="Password" type="password" value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPassword(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {step === 3 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Branding</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Primary color</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input style={inputStyle} type="color" value={primaryColor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPrimaryColor(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Secondary color</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input style={inputStyle} type="color" value={secondaryColor}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setSecondaryColor(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label>Currency</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input style={inputStyle} value={currency}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setCurrency(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input style={inputStyle} placeholder="Slogan" value={slogan}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setSlogan(e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && <p style={{ color: 'red' }}>{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {step > 1 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button style={btnStyle} onClick={prevStep} disabled={loading}>Back</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {step < 3 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button style={btnStyle} onClick={nextStep} disabled={loading}>Next</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {step === 3 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button style={btnStyle} onClick={handleFinish} disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? 'Creating...' : 'Finish & Create Restaurant'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }