import { useEffect, useState } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { supabase } from '../lib/supabaseClient'
import { BACKGROUND_PATTERNS, type BackgroundKey } from '../lib/backgroundPatterns'

const navItems = [
  { to: '/dashboard', label: 'Dashboard', icon: '🏠', end: true },
    { to: '/dashboard/orders', label: 'Orders', icon: '🧾' },
      { to: '/dashboard/menu', label: 'Menu', icon: '🍽️' },
        { to: '/dashboard/tables', label: 'Tables & QR', icon: '🪑' },
          { to: '/dashboard/customers', label: 'Customers', icon: '👥' },
            { to: '/dashboard/payments', label: 'Payments', icon: '💳' },
              { to: '/dashboard/kitchen', label: 'Kitchen', icon: '👨‍🍳' },
                { to: '/dashboard/reports', label: 'Reports', icon: '📊' },
                  { to: '/dashboard/staff', label: 'Staff', icon: '🧑‍💼' },
                    { to: '/dashboard/notifications', label: 'Notifications', icon: '🔔' },
                      { to: '/dashboard/settings', label: 'Settings', icon: '⚙️' },
                      ]

                      export default function DashboardLayout() {
                        const { profile } = useAuth()
                          const navigate = useNavigate()
                            const [bgKey, setBgKey] = useState<BackgroundKey>('terracotta')

                              useEffect(() => {
                                  async function loadTheme() {
                                        if (!profile?.restaurant_id) return
                                              const { data } = await supabase
                                                      .from('restaurants')
                                                              .select('dashboard_background')
                                                                      .eq('id', profile.restaurant_id)
                                                                              .single()

                                                                                    if (data?.dashboard_background) {
                                                                                            setBgKey(data.dashboard_background as BackgroundKey)
                                                                                                  }
                                                                                                      }
                                                                                                          loadTheme()
                                                                                                            }, [profile?.restaurant_id])

                                                                                                              const theme = BACKGROUND_PATTERNS[bgKey]

                                                                                                                async function handleLogout() {
                                                                                                                    await supabase.auth.signOut()
                                                                                                                        navigate('/login')
                                                                                                                          }

                                                                                                                            return (
                                                                                                                                <div style={{ display: 'flex', minHeight: '100vh', background: theme.pageBg, fontFamily: 'system-ui, sans-serif' }}>
                                                                                                                                      <aside
                                                                                                                                              style={{
                                                                                                                                                        width: 220,
                                                                                                                                                                  minWidth: 220,
                                                                                                                                                                            background: theme.sidebar,
                                                                                                                                                                                      color: '#fff',
                                                                                                                                                                                                padding: '20px 12px',
                                                                                                                                                                                                          display: 'flex',
                                                                                                                                                                                                                    flexDirection: 'column',
                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                          <div style={{ padding: '0 8px 20px', borderBottom: '1px solid rgba(255,255,255,0.1)', marginBottom: 16 }}>
                                                                                                                                                                                                                                                    <div style={{ fontSize: 22 }}>🍲</div>
                                                                                                                                                                                                                                                              <h3 style={{ margin: '6px 0 0', fontSize: 16, fontWeight: 700, letterSpacing: 0.3 }}>
                                                                                                                                                                                                                                                                          Restaurant SaaS
                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                    <nav style={{ display: 'flex', flexDirection: 'column', gap: 2, flex: 1 }}>
                                                                                                                                                                                                                                                                                                              {navItems.map((item) => (
                                                                                                                                                                                                                                                                                                                          <NavLink
                                                                                                                                                                                                                                                                                                                                        key={item.to}
                                                                                                                                                                                                                                                                                                                                                      to={item.to}
                                                                                                                                                                                                                                                                                                                                                                    end={item.end}
                                                                                                                                                                                                                                                                                                                                                                                  style={({ isActive }) => ({
                                                                                                                                                                                                                                                                                                                                                                                                  display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                  alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                  gap: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: '10px 12px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textDecoration: 'none',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: isActive ? 600 : 400,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: isActive ? '#fff' : 'rgba(255,255,255,0.72)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: isActive ? theme.accent : 'transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: 'background 0.15s',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ fontSize: 16 }}>{item.icon}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </NavLink>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </aside>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <header
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: '14px 24px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderBottom: '1px solid #eee0d5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: 32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  height: 32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: theme.accentLight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          👤
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ fontSize: 14, color: '#2b1b12' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {profile?.full_name || profile?.name || 'User'}{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ color: '#7c6a5e' }}>({profile?.role || 'owner'})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleLogout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: '1px solid #eee0d5',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: 'transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: theme.accent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '6px 14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 13,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Logout
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <main style={{ flex: 1, padding: 0 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Outlet />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  